### ISSUE TITLE
Implement Series.to_native

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1002]
Currently, we can call `nw.to_native`

It would be more user-friendly to have `Series.to_native` though, I keep finding myself reaching for this

Contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

**Comment by thomend** [comment]
Happy to have a look at this one during the sprints - seems to be a good issue to get familiar with the code base :)
