### ISSUE TITLE
Mark `pipe` as supported in api-completeness

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1006]
This page makes it look like we don't support `pipe` for any backend: https://narwhals-dev.github.io/narwhals/api-completeness/dataframe/

However, we do 😎 That's because we implement it directly in `narwhals/dataframe.py` - can we special-case this one so it shows as completed for all backends?

file to look at: https://github.com/narwhals-dev/narwhals/blob/main/utils/generate_backend_completeness.py

contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

**Comment by Dosenpfand** [comment]
I'd like to try to tackle this one.
