### ISSUE TITLE
test: add hypothesis test for `DataFrame.__getitem__`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1008]
`DataFrame.__getitem__` is...kinda complicated

Let's make a hypothesis test. Something like:

- start with `data = {"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9], "d": [1, 4, 2]}`
- generate a row selection, which could be: a list of integers, an integer, a slice of integers, a numpy array of integers
- generate a column selection, which could be: a list of strings, a list of integers, a slice of integers, a slice of strings, a string, an integer
- check that, for PyArrow and pandas, if we slice using `df[row_selection, column_column_selection]` we get the same result we'd get by using Polars
- check that, for PyArrow and pandas, if we slice using `df[row_selection]` we get the same result we'd get by using Polars
- check that, for PyArrow and pandas, if we slice using `df[column_selection]` we get the same result we'd get by using Polars

This would be _really_ valuable to get right

Contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

**Comment by sjdenny** [comment]
🙋‍♂️ I'm potentially interested in tackling this one.

**Comment by sjdenny** [comment]
> @sjdenny how is it going? I am looking into it as well. I would suggest using the dataframe support form hypothesis to do it

Good - getting into the details of some of the trickier slices :)

**Comment by MarcoGorelli** [comment]
the kinds of things we want to test are, for example:

- `df[[0, 2], 'a']`
- `df[:2]`
- `df[:2, 1:]`
- `df['b']`

and check that these match across dataframe backends

**Comment by MarcoGorelli** [comment]
thanks @sjdenny 

i think we should probably silently allow that at this point, just like we silently allow `df[0]`. it should do the same thing as `df[[0], :]`
