### ISSUE TITLE
docs: add pycapsule interface to related projects

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1011]
https://arrow.apache.org/docs/format/CDataInterface/PyCapsuleInterface.html

Let's add that to https://narwhals-dev.github.io/narwhals/roadmap_and_related/, along with a short description. And also mention that Narwhals supports it for export: https://narwhals-dev.github.io/narwhals/api-reference/dataframe/#narwhals.dataframe.DataFrame.__arrow_c_stream__

contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

**Comment by Morena1996** [comment]
I'll take this to start :)
