### ISSUE TITLE
chore: type `constructor_eager` as `ConstructorEager` instead of `Constructor`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1013]
In here

https://github.com/narwhals-dev/narwhals/blob/9353ef9f681f032feee777fabbb8db8ae98aa79d/tests/utils.py#L20

we have `Constructor`

The task is here it to:
- make `ConstructorEager`, with `IntoDataFrame` instead of `IntoFrame`
- in tests that have `constructor_eager: Any`, use instead `constructor_eager: ConstructorEager`. You may need to import it, see other tests for examples

**Comment by lucianosrp** [comment]
I'll take this one if no one is on it 😊
