### ISSUE TITLE
[Enh]: Allow for kwargs in `LazyFrame.collect`

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#1042]
### Please describe the purpose of the new feature or describe the problem to solve.

Allow to pass collect arguments to the underlying backend method call. For instance with the current implementation it would not be feasible to run polars with its streaming engine.

Ideally this should be as flexible as possible and not necessarily follow the polars API. Reason for this is that each backend `collect`-like function allow for different arguments.

### Suggest a solution if possible.

I suggest two possible implementations:

- sklearn-like: pass arguments with a convention such as `polars__streaming`, `polars__engine`, `dask__optimize_graph` and so on
- engine specific dict:

  ```py
   def compute(
       self,
       *,
       polars_kwargs: dict[str, Any] | None = None,
       dask_kwargs: dict[str, Any] | None = None,
       <engine_kwargs>: dict[str, Any] | None = None,
       ...
       ):
   ```

**Comment by MarcoGorelli** [comment]
yup agree - for duckdb for example there's a variety of formats you may want to collect into

**Comment by FBruzzesi** [comment]
Closing in favor of #1479
