### ISSUE TITLE
[Enh]: Add `.dtypes` and `.typing` to `.stable` API

### ISSUE THREAD

**Issue by schloerke** [narwhals-dev/narwhals#1046]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

Would use it within posit-dev/py-shiny

### Please describe the purpose of the new feature or describe the problem to solve.

Everything else we use is within the v1 object. It would be nice to have the type stability over time

### Suggest a solution if possible.

* Move the [v1](https://github.com/narwhals-dev/narwhals/tree/3f1619da7fc7f8f389e4d00797d029196b9a807b/narwhals/stable) file to of `stable/v1/__init__.py`
* Add `stable/v1/typing.py` to maintain the same "`typing` isn't in the default import" behavior

### If you have tried alternatives, please describe them below.

Curren solution is to import from `nw`

### Additional information that may help us understand your needs.

I enjoy the claim of stability over time. I'd like for my types to fall under the same claim

**Comment by schloerke** [comment]
No hurry on this... just completing the full circle thought around the stable API. 😄

**Comment by FBruzzesi** [comment]
Closed by #1130
