### ISSUE TITLE
Feature: support `.over()` expressions.

### ISSUE THREAD

**Issue by koaning** [narwhals-dev/narwhals#105]
I have this one function that doesn't work in narwhals because it uses `.over()`.

```python
def remove_bots(dataf, max_session_hours=24):
    return (dataf.filter(nw.col("session_length").max().over("player_id") < (max_session_hours * 6)))
```

It gave me this error:

```
Cell In[101], line 10, in remove_bots(dataf, max_session_hours)
      9 def remove_bots(dataf, max_session_hours=24):
---> 10     max_sess = nw.col("session_length").max().over("player_id")
     11     return (dataf.filter(max_sess < (max_session_hours * 6)))

AttributeError: 'Expr' object has no attribute 'over'
```

Is that maybe a feature to add to this project? I can imagine this one could get tricky on the pandas side because it might require a bunch of wrangling with `.groupby().transform()`, but figured I'd ask.

**Comment by MarcoGorelli** [comment]
definitely in scope, thanks! it should just be a `groupby` followed by a `join`, which is all it does in Polars

just to know how to prioritise, do you have a use-case for this?

**Comment by koaning** [comment]
Add sessions to server logs and then remove bots by checking which users have super long sessions. 

Server logs = world of warcraft logs that heartbeat every 10 minutes.

**Comment by MarcoGorelli** [comment]
thanks! and what's the need for making it dataframe-agnostic?

**Comment by koaning** [comment]
Short term: livestream for Friday 😉 

Longer term: the wow dataset is just my standard benchmark dataset. But sessions are universal and many folks will have usecases for them. Including polars users and pandas users. 

That said, logs can get huge, so the polars use-case would be more obvious to me personally.

**Comment by MarcoGorelli** [comment]
are the features in https://github.com/narwhals-dev/narwhals/issues/106#issue-2284125524 all you need? if so, I don't think we're _too_ far off, will see how far I can take it before Friday

anyway, just pushed a new release 😇 now the error message looks better, wish I'd got there before you'd tried it, but I'm glad you flagged this so it could be fixed in time!

**Comment by koaning** [comment]
That said ... I'm dropping this example for Friday. I thought it would make for a nice demo, but at the moment it feels more like a nice example of stuff that doesn't work just yet. My demo also needs things like casting and `.diff()`

**Comment by koaning** [comment]
> are the features in https://github.com/narwhals-dev/narwhals/issues/106#issue-2284125524 all you need?

No. Natural Intelligence is All You Need [tm].

**Comment by koaning** [comment]
Althoug for the Friday demo ... I think [this](https://github.com/narwhals-dev/narwhals/issues/107) would be all I need.
