### ISSUE TITLE
[Enh]: Add `__iter__` support to `Series`

### ISSUE THREAD

**Issue by schloerke** [narwhals-dev/narwhals#1054]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

posit-dev/py-shiny . Not required... just a bonus

### Please describe the purpose of the new feature or describe the problem to solve.

When trying to perform a loop over the cells in a series to check the cell values, it's nice to use `enumerate(x)` to return both the value and the position.

I would like an `__iter__` method for the `nw.Series` object.

```python
for i, val in enumerate(ser):
    ...
```

This also freely extends to other methods like `zip()`. 

### If you have tried alternatives, please describe them below.

I can use a counter on my own

```python
counter = -1
for val in ser:
    counter = counter + 1
    ...
```

**Comment by FBruzzesi** [comment]
Hey @schloerke this should already be possible. Code to replicate:

```py
import narwhals as nw
import pandas as pd
import polars as pl
import pyarrow as pa

data = [1, None, 3]

@nw.narwhalify
def func(series):
    for i, v in enumerate(series):
        print(i, v)

func(pd.Series(data))
# 0 1.0
# 1 nan
# 2 3.0

func(pl.Series(data))
# 0 1
# 1 None
# 2 3

func(pa.chunked_array([[1], [None,3]]))
# 0 1
# 1 None
# 2 3
```

Did you have any issue with it?

**Comment by schloerke** [comment]
I guess my `pylance` / `pyright` type checker is mad about it. (So I did not try to ignore it and see if it correctly functioned.)


Adding types to your example, I get this error:
```
Argument of type "Series" cannot be assigned to parameter "iterable" of type "Iterable[_T@enumerate]" in function "__new__"
  "Series" is incompatible with protocol "Iterable[_T@enumerate]"
    "__iter__" is not presentPylance[reportArgumentType]
```
![Screenshot 2024-09-23 at 4 56 35 PM](https://github.com/user-attachments/assets/31701c69-ce74-4409-bec0-4901dcc9edbe)

---------------------------

I'm using `stable.v1.Series`: https://github.com/narwhals-dev/narwhals/blob/5281c4014e94edc99d40db799514c1772c6e1040/narwhals/stable/v1.py#L345

... which inherits from: https://github.com/narwhals-dev/narwhals/blob/5281c4014e94edc99d40db799514c1772c6e1040/narwhals/series.py#L22 

... which does not have an ``__iter__`` method.

**Comment by MarcoGorelli** [comment]
interesting, thanks! so, in Python, it seems we don't need to implement `__iter__` directly, just `__len__` and `__getitem__` are enough

we should probably implement `__iter__` as well len, to appease the type checker, but also because it might be more efficient (it looks like polars batches this for exactly this reason)

cool, let's do this, and thanks @schloerke for all these great suggestions, really appreciate it!

**Comment by schloerke** [comment]
> thanks @schloerke for all these great suggestions, really appreciate it!

😅 Thank you. I'll keep them coming as I run into them 😃

I appreciate y'all quick decisions and turn around time. #lifegoals
