### ISSUE TITLE
[Doc]: use uv pip in Installation and Quick Start (just as in Contributing.md)

### ISSUE THREAD

**Issue by anopsy** [narwhals-dev/narwhals#1065]
### What type of report is this?

Correction

### Please describe the issue.

Installation and Quick Start uses just `pip`
while CONTRIBUTING.md advices to use `uv pip`
Shall we make it consistent? Or is there a reason to prefer `python -m pip install narwhals` in the Installation and Quick Start?
https://narwhals-dev.github.io/narwhals/installation/

**Comment by MarcoGorelli** [comment]
thanks for raising this!

in the contributing guide, i think it's ok to be more opinionated

in the user guide, on the other hand, i think we should be less opinionated, and more like "whatever tool you use to manage your dependencies, here's how you can install narwhals into it"

**Comment by anopsy** [comment]
Sounds fair! Then I'll close this one

**Comment by MarcoGorelli** [comment]
ah wait sorry I wasn't clear 😄 I think we should include UV as well in the quick start, but perhaps be less opinionated about it (e.g. perhaps there we shouldn't write "recommended")

reopening then if it's ok
