### ISSUE TITLE
Feature: `Expr.str.to_datetime` 

### ISSUE THREAD

**Issue by koaning** [narwhals-dev/narwhals#107]
I get that there's a bunch of expressions missing, but I might prioritise this one since it might allow me to do a bunch of featurization tricks in scikit-learn pipelines.

**Comment by MarcoGorelli** [comment]
> it might allow me to do a bunch of featurization tricks in scikit-learn pipelines

that's the magic word. well, sentence

**Comment by koaning** [comment]
If this is easy to implement: I could make a _really nice_ demo for Friday with this feature.

**Comment by koaning** [comment]
If it isn't, don't sweat it. But this demo feels more realisic/better to show off the vision than the session one.

**Comment by koaning** [comment]
Grand! I'll try and give it another spin tomorrow!
