### ISSUE TITLE
[Enh]: add `maybe_reset_index`

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#1070]
### Please describe the purpose of the new feature or describe the problem to solve.

We have `maybe_get_index` and `maybe_set_index`, yet `maybe_reset_index` is missing.

### Suggest a solution if possible.

Implementation should look something along the following lines:

```py
def maybe_reset_index(df, *, drop: bool):
    native_frame = to_native(df)
    if is_pandas_like_dataframe(native_frame):
        return from_native(native_frame.reset_index(drop=drop))
    return df
```

**Comment by MarcoGorelli** [comment]
`drop=False` would change the number of columns based on the backend, right? I think people usually do `.reset_index(drop=True)`, so perhaps let's just start with that? or is there a use-case for `drop=False`?

in any case, I think in most cases, people wouldn't need to do this, we in Narwhals work around pandas' automated index alignment
