### ISSUE TITLE
feat: allow inspecting inner fields of `nw.Struct`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1107]
in https://github.com/narwhals-dev/narwhals/pull/1104 we allow inspecting the inner dtypes of `nw.List`

We should do the same for `nw.Struct`

**Comment by MarcoGorelli** [comment]
this would be awesome, thanks @DeaMariaLeon !

**Comment by DeaMariaLeon** [comment]
Still working on this.
