### ISSUE TITLE
 feat: allow inspecting the inner type / length of nw.Array

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1108]
in https://github.com/narwhals-dev/narwhals/pull/1104 we allow inspecting the inner dtypes of `nw.List`

We should do the same for `nw.Array`

**Comment by DeaMariaLeon** [comment]
Can I work on this?

**Comment by DeaMariaLeon** [comment]
The polars Array argument "width", changed to "shape" as you know... 
I want to make sure I should use "shape" (as it's more complicated): https://github.com/pola-rs/polars/blob/be5a4b453ca74bb5e0c782c292e9fca6aa60b203/py-polars/polars/datatypes/classes.py#L686C1-L686C25

**Comment by MarcoGorelli** [comment]
ah looks like the docstring is out of date then (https://github.com/pola-rs/polars/blob/be5a4b453ca74bb5e0c782c292e9fca6aa60b203/py-polars/polars/datatypes/classes.py#L688-L695 - hint hint in case it interested you to make a PR to polars...else i can do it, no worries), thanks

🤔 gonna have to think about this one...I think pyarrow only supports width, and trying to convert a 2d array to pyarrow returns a nested fixedsizelist:
```

In [31]: pl.Series([[[1,2]], [[3,4]]], dtype=pl.Array(pl.Int64, shape=(2, 1))).to_arrow()
Out[31]:
<pyarrow.lib.FixedSizeListArray object at 0x7eff183e3a60>
[
  [
    [
      1
    ],
    [
      2
    ]
  ],
  [
    [
      3
    ],
    [
      4
    ]
  ]
]
```

I _think_ it'd be ok to start with just width?
