### ISSUE TITLE
feat: read_csv

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1112]
I was initially hesitant about adding IO methods, the idea being "users provide their own dataframe, we just deal with how to process it", but we already have [from_dict](https://narwhals-dev.github.io/narwhals/api-reference/narwhals/#narwhals.from_dict), and https://github.com/ImperialCollegeLondon/pycsvy/issues/83 and Temporian look like good use cases for `read_csv`

pandas and Polars each have dozens of `read_csv` methods...so we may need to careful here about which ones we add, and perhaps only start with the most common ones

The api would be something like
```python
import pandas as pd
nw.read_csv(file, native_namespace=pd)
```
```python
import polars as pl
nw.read_csv(file, native_namespace=pl)
```

We could do:
- `nw.read_csv`: this is eager-only and always returns `nw.DataFrame`
- `nw.scan_csv`: this is the most generic one, and returns `nw.LazyFrame` if possible (e.g. Polars), else `nw.DataFrame`

---

## Alternatives

Keep the status-quo: users are responsible for doing their own IO

**Comment by lucianosrp** [comment]
I would generally prefer to keep narwhals's _"just-pass-me-the-df"_ philosophy. 

---- 
We could infer which namespace to use based on which module is already imported?  

```python
import pandas as pd
import narwhals as nw

df = nw.read_csv("data.csv") # < uses pandas
```

But  then, what to do with the already imported pandas...? If you are importing it, you might as well use it for I/O

The only major reason to have an I/O support (that I can think of) would be if you would want to replace an entire "narwhals workflow/script" with one setting. 

Other way I could think of:
```python
nw.set_io_backend("pandas")
df = nw.read_csv("data.csv")
```

**Comment by benrutter** [comment]
This sounds interesting - as a library user, how would somebody use it? At the moment, the "give me some-kinda-df, get back some-kinda-df" gives a neat boundary to figure out what the end user is expecting, if I was writing a library with Narwhal's IO, would I do something like this:

```python
def get_a_csv_and_do_some_stuff(namespace: str) -> nw.DataFrame:
    library = get_library_from_namespace_name(namespace)
    return nw.read_csv("data.csv", native_namespace=library).with_columns(z=nw.col("x") * nw.col("y"))
```

**Comment by raisadz** [comment]
I would like to work on this issue

**Comment by MarcoGorelli** [comment]
Thanks! 

> or would that be the library maintainers responsibility?

Yup that's right
