### ISSUE TITLE
feat: `dt.replace_time_zone` and `dt.convert_time_zone`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1119]
this would be useful in plotly

**Comment by FBruzzesi** [comment]
Closed by #1142

**Comment by lxbader** [comment]
I was wondering, is there any reason for `ambiguous` and `non_existent` kwargs not being implemented in `replace_time_zone`? These missing can be a blocker for dealing with conversions between DST and non-DST timezones.

**Comment by MarcoGorelli** [comment]
We should add them could you open a new issue please

**Comment by lxbader** [comment]
Sounds good, see here: https://github.com/narwhals-dev/narwhals/issues/2430
