### ISSUE TITLE
feat: `Series.str.to_datetime`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1120]
This is currently only available on `Expr`

**Comment by FBruzzesi** [comment]
It would be nice to add a couple of parameters while doing so 😉😉 I am looking at `time_zone` and `time_unit` specifically

**Comment by FBruzzesi** [comment]
Regarding adding parameters: it seems that polars is the only one supporting time zones and in general the most flexible.
`time_unit` is allowed for all engines yet it would be a breaking change to modify the default behaviour now.

For the plotly use case, it may be enough to allow for `format=None` and let the engine infer that.
In any case, I think this issue can be closed as it is about adding `to_datetime` to Series str namespace
