### ISSUE TITLE
[Enh]: `Series.scatter()` should always return a new `Series`

### ISSUE THREAD

**Issue by schloerke** [narwhals-dev/narwhals#1154]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

posit-dev/py-shiny

### Please describe the purpose of the new feature or describe the problem to solve.

From [docs](https://github.com/narwhals-dev/narwhals/blob/b961d4eb982b945fcd8efb84f896c275086296c0/narwhals/series.py#L145-L150):
> For some libraries (pandas, Polars), this method operates in-place, whereas for others (PyArrow) it doesn't! We recommend being careful with it, and not relying on the in-placeness. For example, a valid use case is when updating a column in an eager dataframe, see the example below.

I'd like for this behavior to be consistent: use copy on write to return a new Series

Pandas is moving towards copy on write by default in pandas v3. 

When using narwhals's .scatter method, it currently displays a warning about enabling copy on write by default for pandas v2.
```
/venv/lib/python3.12/site-packages/narwhals/_pandas_like/series.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s.iloc[indices] = values
```
[link to related code](https://github.com/narwhals-dev/narwhals/blob/b961d4eb982b945fcd8efb84f896c275086296c0/narwhals/_pandas_like/series.py#L190)

### Suggest a solution if possible.

Change the return type of `.scatter()` to return a new `nw.Series` object.

For pandas, call `pd.options.mode.copy_on_write = True` to enable copy on write today to avoid problems later. 

For polars, update the code to return a new pl.Series object.

### If you have tried alternatives, please describe them below.

Adding `pd.options.mode.copy_on_write = True` line within pandas like `.scatter()` made the warning disappear and gave me expected behavior of a new series. 

I understand this is not a generic solution for pandas-like.

I'm currently getting around it by calling `nw_data = nw_data.clone()` before updating its Series values with `.scatter()`.

**Comment by schloerke** [comment]
A less permanent approach for enabling pandas copy-on-write:

```python
# Require copy on write to be True
with pd.option_context("mode.copy_on_write", True):
    s.iloc[indices] = values
```

**Comment by MarcoGorelli** [comment]
Thanks @schloerke for opening this

For old versions of pandas (which we still support), we wouldn't have the option to enable copy-on-write

Perhaps what we could do is to always make a copy, and update the docstring to say something like

> Note: this method always returns a new Series, without modifying the original one. Using this function in a for-loop is an anti-pattern, we recommend building up your positions and values beforehand and doing an update in one go.
> 
> For example, instead of
> ```python
> for i in [1, 3, 2]:
>     value = some_function(i)
>     s = s.scatter(i, value)
> ```
> prefer
> ```python
> positions = [1, 3, 2]
> values = [some_function(x) for x in positions]
> s = s.scatter(positions, values)
> ```

**Comment by schloerke** [comment]
I like the idea of **always returning a new series**. Then the behavior for `.scatter()` is consistent independent of the backend data frame.

**Comment by Cheukting** [comment]
@MarcoGorelli I will have a look at this is we are ready for imprementation

**Comment by Cheukting** [comment]
@marcoala and I found a solution, PR coming up
