### ISSUE TITLE
[Bug]: Old pandas versions modify in place when using `scatter`

### ISSUE THREAD

**Issue by Cheukting** [narwhals-dev/narwhals#1160]
### Describe the bug

While working on #1159, I discovered that `with_column` changes the DataFrame in place for pandas version 1.1.5 and before, but does not do so for 2.0.3 or after.

### Steps or code to reproduce the bug

See test log here: https://github.com/narwhals-dev/narwhals/actions/runs/11264133905/job/31323491269

### Expected results

Behavior should be consistent through out versions.

### Actual results

`with_column` changes the DataFrame in place for pandas version 1.1.5 and before, but does not do so for 2.0.3 or after.

### Please run narwhals.show_version() and enter the output below.

```shell
testing on https://github.com/Cheukting/narwhals/tree/scatter, expect to be the same as the latest 1.9.2
```

### Relevant log output

```shell
See test log here: https://github.com/narwhals-dev/narwhals/actions/runs/11264133905/job/31323491269
```

**Comment by MarcoGorelli** [comment]
thanks @Cheukting for the report!

i think it's `scatter` that does the inplace modification?

I think this would be solved by https://github.com/narwhals-dev/narwhals/pull/1159, right?

**Comment by Cheukting** [comment]
@MarcoGorelli I don't think it will, when I keep the `with_column` in the test (See test log here: https://github.com/narwhals-dev/narwhals/actions/runs/11264133905/job/31323491269) it failed but when I remove the `with_column` (as in here: https://github.com/narwhals-dev/narwhals/pull/1159/commits/089f31faa063a0c637c0226f7e55eef85ed142be) in the test while keeping the code unchanged, it passes.

I think this is not an issue created by `scatter`

**Comment by MarcoGorelli** [comment]
yup, thanks @Cheukting ! I included a fix in https://github.com/narwhals-dev/narwhals/pull/1159, thanks a tonne for spotting and reporting this, much appreciated 🙏
