### ISSUE TITLE
[Enh]: Narwhals addition to nixpkgs

### ISSUE THREAD

**Issue by dmadisetti** [narwhals-dev/narwhals#1167]
### Please describe the purpose of the new feature or describe the problem to solve.

I just opened a PR to nixpkgs to add narwhals - as it is now a dep of marimo: https://github.com/NixOS/nixpkgs/pull/348012

Let me know if anyone would like to be added as a maintainer. You'll likely get update spam on releases, but it should mostly be automatic

### If you have tried alternatives, please describe them below.

You don't have to be added- you can always add yourself later. I don't mind maintaining- because it's literally just clicking approve on release updates. I do this for marimo already. Just letting you know

**Comment by MarcoGorelli** [comment]
Cool, thanks for doing this and letting us know!

**Comment by MarcoGorelli** [comment]
looks like it's in now?

i think we can close then, but thanks for the issue!
