### ISSUE TITLE
[Bug]: cum_sum expression raises an exception with pandas when 'over' is used

### ISSUE THREAD

**Issue by IsaiasGutierrezCruz** [narwhals-dev/narwhals#1177]
### Describe the bug

The `cum_sum` expression raises an exception when used with the `over` expression.

I did a quick review of the code and I believe this issue can be resolved by simply adding the cum_sum expression name to the dictionary that maps pandas method names to polars method names. I would like to open a pull request to solve this c: 

### Steps or code to reproduce the bug

```
def replicating_error_cum_sum() -> None:
    data = {
        "cat": ["a", "a", "a", "b", "b", "b", "c", "c", "c"],
        'values': [1, 2, 3, 4, 5, 6, 7, 8, None]
    }
    original_data = pd.DataFrame(data)
    df_nw = nw.from_native(original_data)
    df_nw = (
        df_nw
        .with_columns(
            nw.col("values").cum_sum().over("cat")
        )
    )
    print(nw.to_native(df_nw))
```

### Expected results

```
┌─────┬────────┐
│ cat ┆ values │
│ --- ┆ ---    │
│ str ┆ i64    │
╞═════╪════════╡
│ a   ┆ 1      │
│ a   ┆ 3      │
│ a   ┆ 6      │
│ b   ┆ 4      │
│ b   ┆ 9      │
│ b   ┆ 15     │
│ c   ┆ 7      │
│ c   ┆ 15     │
│ c   ┆ null   │
└─────┴────────┘
```

### Actual results

RuntimeError: Failed to aggregated - does your aggregation function return a scalar?

### Please run narwhals.show_version() and enter the output below.

```shell
System:
    python: 3.12.5 (main, Aug 14 2024, 04:32:18) [Clang 18.1.8 ]
executable: /Users/abelisaiasgutierrezcruz/Documents/Proyects/test_narwhals/.venv/bin/python
   machine: macOS-15.0.1-arm64-arm-64bit

Python dependencies:
     narwhals: 1.9.3
       pandas: 2.2.3
       polars: 1.8.2
         cudf: 
        modin: 
      pyarrow: 17.0.0
        numpy: 2.1.1
```

### Relevant log output

```shell
File "/Users/abelisaiasgutierrezcruz/Documents/Proyects/test_narwhals/.venv/lib/python3.12/site-packages/narwhals/_expression_parsing.py", line 98, in <genexpr>
    for sublist in (evaluate_into_expr(df, into_expr) for into_expr in exprs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abelisaiasgutierrezcruz/Documents/Proyects/test_narwhals/.venv/lib/python3.12/site-packages/narwhals/_expression_parsing.py", line 63, in evaluate_into_expr
    return expr._call(df)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^
  File "/Users/abelisaiasgutierrezcruz/Documents/Proyects/test_narwhals/.venv/lib/python3.12/site-packages/narwhals/_pandas_like/expr.py", line 334, in func
    tmp = df.group_by(*keys).agg(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abelisaiasgutierrezcruz/Documents/Proyects/test_narwhals/.venv/lib/python3.12/site-packages/narwhals/_pandas_like/group_by.py", line 76, in agg
    return agg_pandas(
           ^^^^^^^^^^^
  File "/Users/abelisaiasgutierrezcruz/Documents/Proyects/test_narwhals/.venv/lib/python3.12/site-packages/narwhals/_pandas_like/group_by.py", line 184, in agg_pandas
    raise RuntimeError(msg) from exc
RuntimeError: Failed to aggregated - does your aggregation function return a scalar?
```

**Comment by MarcoGorelli** [comment]
thanks for the report! 

> I did a quick review of the code and I believe this issue can be resolved by simply adding the cum_sum expression name to the dictionary that maps pandas method names to polars method names. I would like to open a pull request to solve this c:

sounds great, thanks! 🙏

**Comment by ClaudioSalvatoreArcidiacono** [comment]
Hey @IsaiasGutierrezCruz thanks for raising this issue, I also found it today and it's pretty annoying.

Do you perhaps need some help with it? :)

**Comment by MarcoGorelli** [comment]
hi @ClaudioSalvatoreArcidiacono , may i ask what your use case for this is?

**Comment by ClaudioSalvatoreArcidiacono** [comment]
Hey @MarcoGorelli, glad you asked!

I am building a data science library on narwhals called [`sklearo`](https://github.com/ClaudioSalvatoreArcidiacono/sklearo).

I met this particular issue while trying to implement stratified k fold cross validation in narwhals. The code I am trying to build is something like:

```python
df.with_columns(one=nw.lit(1))
        .with_colums(target=y)
        .with_columns(row_number=nw.col("one").cum_count().over(nw.col("target")))
        .with_columns(
            fold_id=(nw.col("row_number") // n_elements_per_fold)
            + nw.when(nw.col("row_number") % n_elements_per_fold == 0)
            .then(0)
            .otherwise(1)
        )
```

The code is still in draft and it is not doing what I want yet, but ideally I would like to assign a unique row number for each element in each class and then based on that assign a fold to each instance.

**Comment by MarcoGorelli** [comment]
nice, thanks!

ok, gonna see what we can do here, this would be nice to support

**Comment by MarcoGorelli** [comment]
Feel free to, thanks! I think this might be a tricky place to start

**Comment by ClaudioSalvatoreArcidiacono** [comment]
Oh too bad, thanks for the warning.

I will let you know before end of the week if I am up for the challenge.

Any tips on how to solve the issue?

**Comment by FBruzzesi** [comment]
Ciao @ClaudioSalvatoreArcidiacono, really cool and thank you to giving it a try!

> Any tips on how to solve the issue?

I previously took a look at the pandas case, so maybe I can help:

- For pandas (which is probably the main use case), you should follow something similar to what we do in `n_unique` case. However, pandas _drops_ the grouping column for grouped cumulative operations, and the dataframe size doesn't change, hence it could be hard to combine it with other aggregations. At first, I would try to support cumulative operations alone.
- Regarding pyarrow, I don't have any tip as I didn't take a look at that just yet.

I hope this is somewhat useful 😇

**Comment by MarcoGorelli** [comment]
I just gave this a quick go, and we can get
```python
In [3]: df
Out[3]: 
   a  b
0  1  x
1  2  x
2  3  x
3  4  y
4  5  y
5  6  y

In [4]: nw.from_native(df).with_columns(c=nw.col('a').cum_sum().over('b')).to_native()
Out[4]: 
   a  b   c
0  1  x   1
1  2  x   3
2  3  x   6
3  4  y   4
4  5  y   9
5  6  y  15
```

by doing

```diff
diff --git a/narwhals/_pandas_like/expr.py b/narwhals/_pandas_like/expr.py
index 0ddad326..34f2f6c6 100644
--- a/narwhals/_pandas_like/expr.py
+++ b/narwhals/_pandas_like/expr.py
@@ -401,6 +401,30 @@ class PandasLikeExpr:
             )
             return [tmp[name] for name in self._output_names]
 
+        if self._function_name == "col->cum_sum":
+
+            def func(df):
+                res_native = (
+                    df._native_frame.groupby(list(keys), as_index=False)[
+                        self._root_names[0]
+                    ]
+                    .transform("cumsum")
+                    .rename(self._output_names[0], copy=False)
+                    .to_frame()
+                )
+                return [df._from_native_frame(res_native)[self._output_names[0]]]
+
+            return self.__class__(
+                func,
+                depth=self._depth + 1,
+                function_name=self._function_name + "->over",
+                root_names=self._root_names,
+                output_names=self._output_names,
+                implementation=self._implementation,
+                backend_version=self._backend_version,
+                version=self._version,
+            )
+
```

I think `group_by(...).agg` should always aggregate, but in `over` we can allow for expressions which preserve the original length

This needs cleaning up quite a bit, but I think this is doable, and definitely in-scope

**Comment by ClaudioSalvatoreArcidiacono** [comment]
Great news! it would be great to support all sort of cumulative operations (like cum_count, cum_min and cum_max) in a similar way
