### ISSUE TITLE
enh: add `to_py_scalar`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1185]
in the plotly PR () we have

```
def to_py_scalar(scalar_like):
    """If scalar is not python native, tries to convert it to python native."""
    if hasattr(scalar_like, "as_py"):
        return scalar_like.as_py()
    elif hasattr(scalar_like, "item"):
        return scalar_like.item()
    else:
        return scalar_like
```

I think we should have this in Narwhals itself (we _may_ want it to be slightly more robust by doing `isinstance` checks instead of checking for attributes)

**Comment by EdAbati** [comment]
Agreed, happy to take this

**Comment by mscolnick** [comment]
Oh i just hit this in https://github.com/marimo-team/marimo/pull/2643/files#diff-6dd487a960d91d5f0ab620004eb864c819a59cb50e53b4583749a60bec6d7ebf

Awesome to see its prioritized 👍
