### ISSUE TITLE
feat: make `generate_unique_token` public, document it + add examples

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1237]
This is a useful utility function, which is making an appearance in the Plotly PR

So, I think we should make it public, it'll likely be useful in other places

**Comment by aidoskanapyanov** [comment]
Hi, @MarcoGorelli 👋🏻! 
Shall we add a new `narwhals.utils` section to the API reference docs? This section will contain all utility functions that are for public use and documented with examples.

**Comment by MarcoGorelli** [comment]
hey @aidoskanapyanov  - yup, sure!

we may want rename it `generate_temporary_column_name` whilst we're making it public
