### ISSUE TITLE
[Enh]: Increase support for datetime format in pyarrow automatic inference

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#1282]
### Please describe the purpose of the new feature or describe the problem to solve.

As discussed in #1151 [comment](https://github.com/narwhals-dev/narwhals/pull/1195#issuecomment-2443859109), let's try to expand the available formats that we support with automatic inference in pyarrow `str.to_datetime`. Non exhaustive list:

- [x] `"%Y-%m-%dT%H:%M"`
- [ ] `"%Y%m%d%H%M%S"`

**Comment by raisadz** [comment]
I will take it
