### ISSUE TITLE
bug: casting to pl.String gets ignored

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1291]
```
In [20]: import narwhals as nw

In [21]: import polars as pl

In [22]: df = pl.DataFrame({'a': [1,2,3], 'b': [4,5,6]})

In [23]: nw.from_native(df).select(nw.all().cast(pl.String()))
Out[23]:
┌───────────────────────────────────────┐
| Narwhals DataFrame                    |
| Use `.to_native` to see native output |
└───────────────────────────────────────┘

In [24]: nw.from_native(df).select(nw.all().cast(pl.String())).to_native()
Out[24]:
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘
```

This is strange, we should get an error, because the Narwhals syntax is
```
(nw.all().cast(nw.String())
```
not
```
(nw.all().cast(pl.String())
```

**Comment by FBruzzesi** [comment]
`narwhals_to_native_dtype` does not match any type, hence `pl.Unknown` is returned. Maybe we can check if `dtype` is a narwhals datatype, otherwise raise

**Comment by FBruzzesi** [comment]
Edit: If we do a check beforehand, than unknown dtypes cannot be passed anymore. I would be ok with this as we support a subset of polars. However I am not sure about all the downstream use cases. I can open a PR and move the conversation there

**Comment by MarcoGorelli** [comment]
yup that's what I had in mind, sorry for not being clear, thanks!

when i used narwhals as a user I sometimes confused `pl` with `nw`, but I'd never use `pd` instead, so I think this would already address what's probably the most common user error
