### ISSUE TITLE
docs: return values don't show up in docs

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1293]
edit by @marenwestermann

Add a "Returns" section to the doc strings of functions and methods which concisely describes what is being returned.
Start with one or two functions at a time. Once you feel familiar with the documentation process you can update several functions at a time (remember to ideally keep your pull requests small). For more details and an example see below. 

Note: There are a few functions/ methods where the documentation of the arguments is missing too. It would be great if you could add this too in case it's missing. 

List of functions/ methods that need the "Returns"documentation: 
- dataframe.py 
    DataFrame:
	- [x] lazy
	- [x] to_pandas
	- [x] write_csv
	- [x] write_parquet
	- [x] to_numpy
	- [x] shape
	- [x] get_column
	- [x] to_dict
	- [x] row
	- [x] pipe
	- [x] drop_nulls
	- [x] with_row_index
	- [x] schema
	- [x] collect_schema
	- [x] columns
	- [x] rows
	- [x] iter_rows
	- [x] select
	- [x] rename
	- [x] head
	- [x] tail
	- [x] drop
	- [x] unique
	- [x] filter
	- [x] sort
	- [x] is_duplicated
	- [x] is_empty
	- [x] is_unique
	- [x] null_count
	- [x] item
	- [x] clone
	- [x] gather_every
	- [x] to_arrow
	- [x] sample
	- [x] unpivot
    
    LazyFrame
	- [x] pipe
	- [x] drop_nulls
	- [x] with_row_index
	- [x] schema
	- [x] collect_schema
	- [x] columns
	- [x] select
	- [x] rename
	- [x] head
	- [x] tail
	- [x] drop
	- [x] filter
	- [x] group_by
	- [x] sort
	- [x] clone
	- [x] lazy
	- [x] gather_every
	- [x] unpivot
- series.py
    Series
	- [x] abs
	- [x] alias
	- [x] all
	- [x] any
	- [x] arg_true
	- [x] cast
	- [x] clip
	- [x] count
	- [x] cum_count
	- [x] cum_max
	- [x] cum_min
	- [x] cum_prod
	- [x] cum_sum
	- [x] diff
	- [x] drop_nulls
	- [x] dtype
	- [x] fill_null
	- [x] filter
	- [x] gather_every
	- [x] head
	- [x] is_between
	- [x] is_duplicated
	- [x] is_empty
	- [x] is_first_distinct
	- [x] is_in
	- [x] is_last_distinct
	- [x] is_null
	- [x] is_sorted
	- [x] is_unique
	- [x] item
	- [x] len
	- [x] max
	- [x] mean
	- [x] median
	- [x] min
	- [x] mode
	- [x] n_unique
	- [x] name
	- [x] null_count
	- [x] pipe
	- [x] quantile
	- [x] rename
	- [x] replace_strict
	- [x] round
	- [x] sample
	- [x] scatter
	- [x] shape
	- [x] shift
	- [x] sort
	- [x] std
	- [x] sum
	- [x] tail
	- [x] to_arrow
	- [x] to_dummies
	- [x] to_frame
	- [x] to_list
	- [x] to_numpy
	- [x] to_pandas
	- [x] unique
	- [x] value_counts
	- [x] zip_with

    SeriesCatNamespace
	- [ ] get_categories

    SeriesStringNamespace
	- [ ] contains
	- [ ] ends_with
	- [ ] head
	- [ ] len_chars
	- [ ] replace
	- [ ] replace_all
	- [ ] slice
	- [ ] starts_with
	- [ ] strip_chars
	- [ ] tail
	- [ ] to_datetime
	- [ ] to_lowercase
	- [ ] to_uppercase

    SeriesDateTimeNamespace
	- [ ] convert_time_zone
	- [ ] date
	- [ ] day
	- [ ] hour
	- [ ] microsecond
	- [ ] millisecond
	- [ ] minute
	- [ ] month
	- [ ] nanosecond
	- [ ] ordinal_day
	- [ ] replace_time_zone
	- [ ] second
	- [ ] timestamp
	- [ ] to_string
	- [ ] total_microseconds
	- [ ] total_milliseconds
	- [ ] total_minutes
	- [ ] total_nanoseconds
	- [ ] total_seconds
	- [ ] year

**Comment by marenwestermann** [comment]
I can start working on this one. Just for clarification:
- this should be done for all public functions that are exposed to the user, right? 
- you follow the Google docstring format, correct?

**Comment by MarcoGorelli** [comment]
wonderful, thanks!

yes, that's right!

**Comment by MarcoGorelli** [comment]
I've done the ones in `expr.py` as a lot of them weren't really obvious (e.g. a newcomer would not know what to expect the return type of `nw.all` to be) - we're getting a lot more interest in Narwhals recently so I think it's important for those to be accurate

The rest we can do at the sprint - thanks @marenwestermann for listing all the ones that need doing! 🙏

**Comment by marenwestermann** [comment]
Yeah, I was also thinking that the ones in `expr.py` might potentially be a bit (too) hard for newcomers. I'll update the list accordingly then (I saw that you already removed `expr.py` from the list but the ones for `Series` for example still need documentation).

**Comment by marenwestermann** [comment]
I thought I'll make several PRs for this issue, one for each of the classes listed above. I started working on the documentation for the DataFrame class.
