### ISSUE TITLE
api: rename `strict` to `pass_through`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1306]
Context: in both the Plotly and the Altair PRs, some maintainers expressed some surprised at what `strict=False` does

Polars does have `strict` parameter in a few places, but it doesn't exactly match ours in `from_native`:
- for `strict=True`, both Narwhals.from_native and Polars' Series constructor raise
- for `strict=False`, then in Polars, non-coercible types are set to `null`, whereas in `narwhals.from_native` we just pass things through unchanged

So, `pass_through` is probably a better name

An alternative would be to be to just make it strict by default and let people do `try-except`, but tbh I'm not a huge fan of encouraging try-except, it's kinda error-prone, and it's easy to think you're catching one error but are actually catching another one entirely

**Comment by MarcoGorelli** [comment]
in accordance with the stability principle, the idea would be to:
- introduce `pass_through` alongside `strict`
- `nw.from_native` raises a `DeprecationWarning` if `strict` is passed, whereas `nw.stable.v1` doesn't

**Comment by MarcoGorelli** [comment]
working on this,

**Comment by FBruzzesi** [comment]
Closed by #1312
