### ISSUE TITLE
enh: add `maintain_order` to Expr.unique and Series.unique

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1328]
As requested here https://github.com/plotly/plotly.py/pull/4790#issuecomment-2459974589

We already have `maintain_order` for `DataFrame.unique`, my concern is that for some libraries this may turn out to not be guaranteed (and for there to not be any option to guarantee it)

However, a workaround like
```python
token = f'{s.name}_tmp'
s.to_frame().with_row_index(token).unique(col).sort(token).get_column(col)
```
should always be possible, were some library to stop guaranteeing it

It's not clear to me whether PyArrow makes any guarantees - we can always just use it for now, and if it stop making such guarantees, we use the workaround above https://github.com/apache/arrow/issues/44663

**Comment by EdAbati** [comment]
To clarify, we just want this option for eager DataFrames/Expr, right?

**Comment by raisadz** [comment]
I would like to work on it if that's ok
