### ISSUE TITLE
chore: use `issue_deprecation_warning` in `generate_unique_token`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1357]
In

https://github.com/narwhals-dev/narwhals/blob/0929d5275c3522822868434a18fcc4ec1ea2ea22/narwhals/utils.py#L541-L546

we should be using `issue_deprecation_warning` from `narwhals.utils`, so that the stacklevel is set correctly

check 

https://github.com/narwhals-dev/narwhals/blob/0929d5275c3522822868434a18fcc4ec1ea2ea22/narwhals/utils.py#L676-L681

for an example of how to use it

**Comment by AlessandroMiola** [comment]
Closed by #1359.
