### ISSUE TITLE
api: "unstable" features

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1367]
I'm slightly hesitant about how to merge #1298 and #1290 - rolling_mean is marked as unstable in Polars. ewm_mean isn't, but follows the api kind of API style

I do think we should merge them, I just think we need a way to signal that we won't make the same kinds of promises for them as we do for the rest of the API in `stable.v1`

So, I'm tempted to say:
- let's wait for some decision / further discussion on https://github.com/plotly/plotly.py/issues/4834
- we can discuss the Narwhals unstable API

I'm sorry for the delay here in merging these PRs

**Comment by FBruzzesi** [comment]
> I'm sorry for the delay here in merging these PRs

No need to be sorry, I think #1290 was not even discussed fully (e.g. in which way we want to implement rolling for pyarrow backend).

Regarding _how_ to mark features as unstable, which options do we have? Adding a warning/disclaimer in the docstrings and docs is the bare minimum, aside that:

- Raising a warning might be _too_ much and too strong for a user.
- Raising a warning _only_ in the stable API i.e. if used in `narwhals.stable.v1`, but let it go silently if called from `narwhals`?

I would say this second option could be a compromise?

**Comment by DeaMariaLeon** [comment]
Is this decided then?: "define a NarwhalsUnstableWarning class, and advise users to silence warnings of that class if they're OK with using an experimental feature"

**Comment by MarcoGorelli** [comment]
Yeah I think this is probably the best way to go about it, thanks for the discussion

Are you interested in adding `NarwhalsUnstableWarning` to your PR (it could be defined in `narwhals/_exceptions`), or in adding it as a precursor PR?

**Comment by DeaMariaLeon** [comment]
So, the `NarwhalsUnstableWarning` is being done on #1395, I don't need to do this right @MarcoGorelli ?

**Comment by MarcoGorelli** [comment]
i think you're right - i'll change the assignment then, once we get that in we can ship ewm_mean too 🚀
