### ISSUE TITLE
DOC Maybe have other ways than `narwhalify` in the tutorial?

### ISSUE THREAD

**Issue by adrinjalali** [narwhals-dev/narwhals#1372]
This is my first actual reading of the docs with a usecase where I'd use narwhals. Going through the README, I was told to check a tutorial:

https://github.com/narwhals-dev/narwhals/blob/4c2b60ed5606a3cad119ae72543d070886be10c1/README.md?plain=1#L95-L98

But the tutorial only has this kind of pattern AFAICT:

```py
@nw.narwhalify
def func(df: FrameT) -> FrameT:
    return df.select(
        a_sum=nw.col("a").sum(),
        a_mean=nw.col("a").mean(),
        a_std=nw.col("a").std(),
    )
```

while I wold have expected to also been shown examples of non-decorator ways of doing things, which I think is `from_native`.

**Comment by adrinjalali** [comment]
@marenwestermann wanna have a look maybe? 😁

**Comment by marenwestermann** [comment]
It's good to get some feedback on this. Given that many people seem to find it easier to use `from_native` and `to_native` I guess it's better to go back to that as a default. Updating the documentation accordingly could be another meta-issue for the planned sprint or would you prefer to do this earlier @MarcoGorelli ? If we want to use this for the sprint I can make an issue with a list of functions/ methods that would need the update. 
PS: I still love the narwhalify decorator! I had a good laugh when I first came across it. 😄

**Comment by MarcSkovMadsen** [comment]
For the examples using `FrameT` are hard to understand as I get no help from my editor. My editor does not understand what `value` in the example is. I.e. I have to refer to the documentation to understand what goes on and what can be done.

![image](https://github.com/user-attachments/assets/004fb268-e327-4697-8d62-e6358d74e6e8)

Furthermore I often have example where a function types more types than something that can be converted to a dataframe:

A dummy example is below:

```python
import narwhals as nw
from narwhals.typing import FrameT

def transform(value: str | FrameT)->str:
    if isinstance(value,str):
        return f"Hello '{str}'"
    elif isinstance(value, FrameT):
        value.sum()
    else:
        msg = f"Type '{type(value)}` is not supported."
        raise NotImplementedError()
    
    return 
```

I would be really nice to be shown how to implement examples like these.

**Comment by MarcoGorelli** [comment]
Thanks @MarcSkovMadsen ! I've added docstrings for typing objects, now you'll get something like this:

![image](https://github.com/user-attachments/assets/013269fd-9a6d-4b87-babe-6e48965efb31)

Not sure I follow your example though - `.sum` isn't defined on `DataFrame`, just on `Expr` / `Series`. If you could show a more realistic example, I'd be happy to help!
