### ISSUE TITLE
Selectors

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#139]
# Description

Testing the territory for _selectors_. 

- polars has its long awesome list of [selectors](https://docs.pola.rs/py-polars/html/reference/selectors.html), among which `by_dtype`
- pandas-like apis have `select_dtypes` ([pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html), [modin](https://modin.readthedocs.io/en/0.13.3/supported_apis/dataframe_supported.html?highlight=select_dtypes#pd-dataframe-supported-apis), [cudf](https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.dataframe.select_dtypes/))

Adding something like `narwhals.selectors.by_dtype` to match polars should be fairly easy?

## Disclaimer

Very selfish request in order to migrate [`sklego.preprocessing.PandasTypeSelector`](https://github.com/koaning/scikit-lego/blob/main/sklego/preprocessing/pandastransformers.py#L161)

**Comment by MarcoGorelli** [comment]
Sounds good to me! I think this would require reworking the `PandasExpr` logic a bit...but it should be doable!

**Comment by MarcoGorelli** [comment]
selectors are in now - for specific missing features, we can use smaller issues like #224 . great request, thanks!
