### ISSUE TITLE
docs: bikeshed on good name for example function in docs

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1407]
Related to https://github.com/narwhals-dev/narwhals/pull/1406#issuecomment-2486295148

Currently the docstring examples of use `func` or `my_library_agnostic_function`

Let's discuss on Friday's call what to name the functions

In the meantime I'm pretty keen on not having `narwhalify` in the docstrings, so we can showcase type annotations and keep things simple and non-magical for newcomers

**Comment by FBruzzesi** [comment]
This would be much more effort, yet in my opinion a descriptive function name would be related to the method it performs.

E.g. for `Series.value_counts` method, in the docstring example something along the lines of `def agnostic_value_counts(s_native): ...` would be descriptive for me.

Of course if we manage to find some unique and appealing name that would be grand!
