### ISSUE TITLE
`with_columns(..)` raises `Expected IntoExpr, got ...` if native is not polars 

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#141]
# Description

I am having quite a hard time to create a new column if the native frame is not polars.

## Example

```py
import narwhals as nw
import numpy as np
import polars as pl

frame = pl.DataFrame({"a": [1,2,3]})

nw_frame = nw.from_native(frame)
nw_frame.with_columns(b=list("abc"), c=np.ones(3))
```

This is all well and good, but if I switch to pandas it yells

```py
import pandas as pd
frame = pd.DataFrame({"a": [1,2,3]})

nw_frame = nw.from_native(frame)
nw_frame.with_columns(b=list("abc"), c=np.ones(3))
```
> AssertionError: Expected IntoExpr, got <class 'list'>
>
> AssertionError: Expected IntoExpr, got <class 'numpy.ndarray'>

Am I missing something?

**Comment by MarcoGorelli** [comment]
thanks for spotting this! indeed, if the input is a sequence, we should probably  just call the underlying library's `Series` constructor on it

**Comment by MarcoGorelli** [comment]
partially addressed in https://github.com/narwhals-dev/narwhals/pull/144 (at least, numpy array input)

**Comment by FBruzzesi** [comment]
That was fast 👀

**Comment by FBruzzesi** [comment]
Closing this as we can use:

```py
plx = nw.get_native_namespace(X)
plx.Series([1,2,3])
```
