### ISSUE TITLE
[Enh]: Add FireDucks support

### ISSUE THREAD

**Issue by ndrezn** [narwhals-dev/narwhals#1413]
FireDucks is yet another high-performance dataframe library. It intends to have API compatibility with Pandas. See: https://fireducks-dev.github.io/docs/user-guide/01-intro/

Here's the launch post: https://www.nec.com/en/press/202310/global_20231019_01.html

It's not fully mature yet, and only supports Linux. But it looks like supporting FireDucks could (eventually) be within the scope of the Narwhals project.

FireDucks is BSD-3 licensed: https://github.com/fireducks-dev/fireducks

For now it only has a Linux build.

**Comment by FBruzzesi** [comment]
If anyone is interested in picking this up, I made a [branch](https://github.com/narwhals-dev/narwhals/tree/feat/fireducks) some time ago when someone suggested that on discord. I just merged with the main and solved conflicts and pushed it to the repo.

This is the "out of the box" pandas-like library onboarding, therefore there are around 50ish failing tests.

**Comment by MarcoGorelli** [comment]
thanks! tbh I don't think fireducks is yet significant enough that we should take on long-term support of it, and more importantly, it's not open source

this might be a good use-case for the standardisation / reference implementation effort brought up in https://github.com/narwhals-dev/narwhals/discussions/1370

I kinda feel like generally it's OK for us to take on widely used open source projects, but when a project is neither widely used nor open source, then I think it's up to them to do the work

**Comment by MarcoGorelli** [comment]
Just checked and it's fairly easy to allow fireducks to just work, so I've done that it https://github.com/narwhals-dev/narwhals/pull/1439

looks like they return incorrect results on pretty simple tasks:
```python
(polars-api-compat-dev) marcogorelli@DESKTOP-U8OKFP3:~/polars-api-compat-dev$ cat f.py 
# ruff: noqa
from __future__ import annotations

import pandas as pd

print(pd.Series([1], name='a').where(pd.Series([False]), pd.Series([4])))
(polars-api-compat-dev) marcogorelli@DESKTOP-U8OKFP3:~/polars-api-compat-dev$ python f.py 
0    4
Name: a, dtype: int64
(polars-api-compat-dev) marcogorelli@DESKTOP-U8OKFP3:~/polars-api-compat-dev$ python -m fireducks.pandas f.py 
0   NaN
Name: a, dtype: float64
```
, I've reported this to them

Thanks for the request! Closing as completed in #1439 then
