### ISSUE TITLE
feat: make `dependencies` available under `narwhals.stable.v1` for type checkers

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1426]
Currently
```
from narwhals.stable.v1.dependencies import is_pandas_like_dataframe
````
raises, but 
```
from narwhals.stable.v1 import dependencies
```
passes

**Comment by dangotbanned** [comment]
I've tried a few variants of import statements but not had any luck.

I think adding an `__all__` would do the trick though, maybe one of the *idoms* from https://microsoft.github.io/pyright/#/typed-libraries?id=library-interface


Although making both `mypy` and `pyright` happy is more of a task

https://github.com/vega/altair/blob/c41e29e0bfa9e34d942635e574b2accfd9f2de0d/tools/generate_schema_wrapper.py#L1103-L1139

**Comment by MarcoGorelli** [comment]
thanks for taking a look at that - i think we have it:

https://github.com/narwhals-dev/narwhals/blob/78f1a8dd9cfed8f8e6c62811e431031b64310313/narwhals/__init__.py#L109

we may just need to make a `dependencies.py` file in which we do the import, that'd probably be the simplest thing

**Comment by dangotbanned** [comment]
> thanks for taking a look at that - i think we have it:
> 
> https://github.com/narwhals-dev/narwhals/blob/78f1a8dd9cfed8f8e6c62811e431031b64310313/narwhals/__init__.py#L109
> 
> we may just need to make a `dependencies.py` file in which we do the import, that'd probably be the simplest thing

Apologies if I've misunderstood your comment

I meant adding an `__all__` here

https://github.com/narwhals-dev/narwhals/blob/6946e26c1e6d3b5663d849534a4bfcfd9b82d1cb/narwhals/stable/v1/__init__.py#L69-L80

**Comment by dangotbanned** [comment]
> sorry i may have misunderstood myself - don't we have it at the bottom of the file?
> 
> https://github.com/narwhals-dev/narwhals/blob/6946e26c1e6d3b5663d849534a4bfcfd9b82d1cb/narwhals/stable/v1/__init__.py#L3179-L3247

ah there it is 😅

**Comment by dangotbanned** [comment]
@MarcoGorelli I haven't checked the other submodules, but do these all have the same issue?


https://github.com/narwhals-dev/narwhals/blob/6946e26c1e6d3b5663d849534a4bfcfd9b82d1cb/narwhals/stable/v1/__init__.py#L15-L17


Great to see #1430

**Comment by MarcoGorelli** [comment]
for those we already have dedicated files
