### ISSUE TITLE
enh: create dataframe from 2D numpy array and column names

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1434]
For classical numpy dtypes in pandas, this should be more efficient than forcing slices + dicts

Spotted in Prophet

Desired syntax:
```python
import narwhals as nw
import numpy as np
import pandas as pd

arr = np.zeros([[1,2,3], [4,5,6]])
df = nw.from_2d_array(arr, column_names=['a', 'b', 'c'])
```
It should also be possible to pass in `dtype` as an argument - if not passed, it'll be autoinferred
```python
import narwhals as nw
import numpy as np
import pandas as pd

arr = np.zeros([[1,2,3], [4,5,6]])
df = nw.from_2d_array(arr, column_names=['a', 'b', 'c'], dtype=nw.Float64)
```

**Comment by FBruzzesi** [comment]
Should this emulate [`polars.from_numpy`](https://docs.pola.rs/api/python/stable/reference/api/polars.from_numpy.html) with the extra `namespace` argument?

**Comment by MarcoGorelli** [comment]
yup good shout!

**Comment by raisadz** [comment]
If no one has started working on it yet, I would like to take it
