### ISSUE TITLE
[Doc]: What big projects use narwhals now?

### ISSUE THREAD

**Issue by koaning** [narwhals-dev/narwhals#1450]
### What type of report is this?

Improvement

### Please describe the issue.

It might be nice to have a spot on the docs that highlight which projects use Narwahls as a dep. I am partially asking this as a curiosity, but having such a page might also help motivate others to join the fun. 

### If you have a suggestion on how it should be, add it below.

Maybe a dedicated page?

**Comment by MarcoGorelli** [comment]
thanks for the request - we have https://github.com/narwhals-dev/narwhals?tab=readme-ov-file#used-by, but maybe this should be mirrored in the docs too

**Comment by anopsy** [comment]
Yes, I was also looking for that in the docs, and then realized we only have that in the README

**Comment by MarcoGorelli** [comment]
here now, thanks Francesco https://narwhals-dev.github.io/narwhals/ecosystem/#used-by
