### ISSUE TITLE
perf: Should we be rechunking in concat for PyArrow?

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1463]
Polars doesn't rechunk by default in concat: https://docs.pola.rs/api/python/stable/reference/api/polars.concat.html

But, we currently rechunk for PyArrow

Should we? Investigations into whether we should would be welcome

**Comment by FBruzzesi** [comment]
I wonder if the best way of going about this is to run the test suite with arrow tables with multiple chunks. At the current moment I don't think we have a good sense if all the methods would run smoothly

**Comment by MarcoGorelli** [comment]
we can probably use the tpc-h q7 for this

**Comment by FBruzzesi** [comment]
q7 seems to run fine. At the end, that's why arrow columns are chunked arrays, isn't it? And all our series/expr operations are based on chunked array anyway

**Comment by MarcoGorelli** [comment]
cool, let's undo the rechunking then
