### ISSUE TITLE
chore: in `_expr`, rename `_pandas_series` to `_compliant_series`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1499]
We have an attribute there called `_pandas_series`, but what it stores is actually a CompliantSeries (see [how it works](https://narwhals-dev.github.io/narwhals/how_it_works/) for some explanation). So, we should rename it to `_compliant_series`

Similarly, for `PandasLikeExprCatNamespace`, we should rename `_expr` to `_compliant_expr`

The list of classes where this needs doing is:
- [ ] PandasLikeSeriesCatNamespace
- [ ] PandasLikeSeriesDateTimeNamespace
- [ ] PandasLikeSeriesStringNamespace
- [ ] PandasLikeExprCatNamespace
- [ ] PandasLikeExprDateTimeNamespace
- [ ] PandasLikeExprStringNamespace
- [ ] PandasLikeExprNameNamespace
- [ ] ArrowSeriesCatNamespace
- [ ] ArrowSeriesDateTimeNamespace
- [ ] ArrowSeriesStringNamespace
- [ ] ArrowExprCatNamespace
- [ ] ArrowExprDateTimeNamespace
- [ ] ArrowExprStringNamespace
- [ ] ArrowExprNameNamespace
- [ ] PolarsSeriesCatNamespace
- [ ] PolarsSeriesDateTimeNamespace
- [ ] PolarsSeriesStringNamespace
- [ ] PolarsExprCatNamespace
- [ ] PolarsExprDateTimeNamespace
- [ ] PolarsExprStringNamespace
- [ ] PolarsExprNameNamespace
- [ ] DaskExprCatNamespace
- [ ] DaskExprDateTimeNamespace
- [ ] DaskExprStringNamespace
- [ ] DaskExprNameNamespace

If you're using vscode, you can do the renaming F2

---

I'd suggest choosing 3-5 of these and submitting a PR for them. Please leave a comment with which ones you chose

**Comment by Ankush1oo8** [comment]
Can I do this

**Comment by skritsotalakis** [comment]
can work on this for PydataGlobal sprint

**Comment by olp-cs** [comment]
The only remaining subtask is `DaskExprCatNamespace`, but I didn't find it in the `main` branch.

**Comment by MarcoGorelli** [comment]
thanks @olp-cs  for taking a look! indeed, we don't have that one, so the issue can be closed

if you fancied another contribution, https://github.com/narwhals-dev/narwhals/issues/1556 would be a great one to get in, feel free to ask if anything trips you 🙏
