### ISSUE TITLE
[Doc]: Add a docstring example in `narwhals.dtypes` for Unknown 

### ISSUE THREAD

**Issue by anopsy** [narwhals-dev/narwhals#1507]
### What type of report is this?

Improvement

### Please describe the issue.

Thank you for contributing to Narwhals
May the Undwerwater Unicorn Magic be with You! 🌊🦄

Add a docstring example for Unknown - dtype, that will be visible here:
https://narwhals-dev.github.io/narwhals/api-reference/dtypes/#narwhals.dtypes.Unknown

Check https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md
for instructions how to set up your environment

Check https://narwhals-dev.github.io/narwhals/api-reference/dtypes/#narwhals.dtypes.List
as a reference of how it should look like

and https://github.com/narwhals-dev/narwhals/blob/main/narwhals/dtypes.py
as a reference on how to create docstrings

If you need any help just let us know!
Happy Contributing💻🎉

**Comment by camriddell** [comment]
Was taking a look at this and wanted to confirm that the following would be a decent example that users might encounter:

```python
>>> import narwhals as nw
>>> import pandas as pd
>>> ser_pd = pd.Series(pd.period_range('2000-01', periods=4, freq='M'))
>>> nw.from_native(ser_pd, series_only=True).dtype
Unknown
```

Unfortunately I can't seem to trick an Unknown conversion from either Polars or PyArrow with out some more complicated examples. I figured that the primary trigger for this in Narwhals would be from individuals who work with extension/custom datatypes.

**Comment by MarcoGorelli** [comment]
thanks @camriddell ! I think that'd already be a useful addition, it shows the kind of code which results in `nw.Unknown`
