### ISSUE TITLE
tests: Add test for `Expr.is_in()` with `Series` input

### ISSUE THREAD

**Issue by CangyuanLi** [narwhals-dev/narwhals#1524]
### Describe the bug

Hi, thanks for the awesome package! I noticed a bug with `.is_in()` when the Narwhals DataFrame is Polars-backed. When `.si_in()` is passed a Narwhals Polars-backed Series, it errors with 

```
ValueError: can only call '.item()' if the Series is of length 1, or an explicit index is provided
```

You can see the behavior in the code below, which shows that it works when passed a list or a Polars Series. The code also shows the same bug does not happen with a Narwhals Pandas-backed Series.

### Steps or code to reproduce the bug

```python
import narwhals as nw
import narwhals.typing as nwt
import pandas as pd
import polars as pl

# Pandas

df = pd.DataFrame({"a": [1, 2, 3]})
df2 = pd.DataFrame({"b": [1, 0, 2]})
nw_df = nw.from_native(df)
nw_df2 = nw.from_native(df2)

print(nw_df.filter(nw.col("a").is_in(df2["b"])).to_native())
print(nw_df.filter(nw.col("a").is_in(nw_df2["b"])).to_native())

# Polars

df = pl.DataFrame({"a": [1, 2, 3]})
df2 = pl.DataFrame({"b": [1, 0, 2]})
nw_df = nw.from_native(df)
nw_df2 = nw.from_native(df2)

print(nw_df.filter(nw.col("a").is_in(df2["b"])).to_native())
print(nw_df.filter(nw.col("a").is_in(nw_df2["b"].to_list())).to_native())
print(nw_df.filter(nw.col("a").is_in(nw_df2["b"])).to_native())  # doesn't work!
```

### Expected results

I expect the Pandas and Polars-backed frames to be the same.

### Actual results

ValueError: can only call '.item()' if the Series is of length 1, or an explicit index is provided (Series is of length 3)

### Please run narwhals.show_version() and enter the output below.

```shell
System:
    python: 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]
executable: /opt/conda/envs/Python-3.10-Premium/bin/python
   machine: Linux-4.18.0-372.98.1.el8_6.x86_64-x86_64-with-glibc2.28

Python dependencies:
     narwhals: 1.15.1
       pandas: 2.2.3
       polars: 1.16.0
         cudf: 
        modin: 
      pyarrow: 18.1.0
        numpy: 1.26.4
```

**Comment by MarcoGorelli** [comment]
thanks @CangyuanLi for your kind works, and for your report

I just tried this on the `main` branch, and it looks like it works - just gonna see when it might have got fixed

**Comment by MarcoGorelli** [comment]
In fact, it also works with 1.15.2 - could you try upgrading your Narwhals version please? `pip install -U narwhals`

**Comment by CangyuanLi** [comment]
Oh it does, thanks so much!

**Comment by MarcoGorelli** [comment]
we don't have an explicit test case for this though, it looks like it got fixed as a positive side effect of https://github.com/narwhals-dev/narwhals/pull/1480, good one @FBruzzesi !

reopening then as a "needs test" issue

**Comment by FBruzzesi** [comment]
Long term plan would be to add support for expr's as well, similar to what's mentioned in #730

**Comment by jddelaune** [comment]
I'll give this a shot!

**Comment by skritsotalakis** [comment]
Hi!
Is this still available?

**Comment by MarcoGorelli** [comment]
yup!
