### ISSUE TITLE
docs: add link to "adding a new ssh key to your github account"

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1526]
We should add a link to [how to add a new ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) in the contributing guide, as it's come up a couple of times that people didn't know they had to do this in sprints

**Comment by czhanger** [comment]
May I handle this issue?
