### ISSUE TITLE
docs: add docstring for Series.__getitem__

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1553]
We're missing a docstring for Series.__getitem__, let's add one!

**Comment by TimOsahenru** [comment]
do you mean PolarsSeries.getitem ?

**Comment by MarcoGorelli** [comment]
no, `narwhals.Series.__getitem__` https://narwhals-dev.github.io/narwhals/api-reference/series/#narwhals.series.Series.__getitem__
