### ISSUE TITLE
feat: IO follow-ups (read_csv args, read_parquet)

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1556]
There's a few follow-up tasks from #1551 :

- [ ] add `**kwargs` to the `read_csv` signature - these kwargs can be backend-specific and just get passed down as they are
- [ ] add `read_parquet` / `scan_parquet`
- [ ] use `nw.read_parquet` in https://github.com/narwhals-dev/narwhals/blob/main/tpch/execute.py

**Comment by dangotbanned** [comment]
Hopefully these resources can be of use:

Pretty wide range of `.csv` (and `.tsv`) files to test (https://github.com/vega/vega-datasets/tree/efa018a7098f5c463959db2edf6d4d5c8a40380f/data)
Also some larger `.csv` and `.parquet` (https://github.com/uwdata/mosaic/tree/57580776bcf69a37b6c3c0724a970d4db7d8a7fd/data)

---

For why you don't wanna support `nw.read_json` 😉, see
- https://github.com/vega/altair/blob/75bf2bad9d5d8f59c6084f1f58686085409f604c/altair/datasets/_readers.py#L351
- https://github.com/vega/altair/blob/75bf2bad9d5d8f59c6084f1f58686085409f604c/altair/datasets/_readers.py#L305

**Comment by raisadz** [comment]
If no one has started working on it yet, I will take this issue
