### ISSUE TITLE
[Enh]: Unified memory API

### ISSUE THREAD

**Issue by paulduf** [narwhals-dev/narwhals#1563]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

It's still at very early stage so I cannot provide a link.

### Please describe the purpose of the new feature or describe the problem to solve.

I'd rather describe what I have now and ask if it is something that makes sense to have in `narwhals`.

I have this simple function to return the size in megabytes of a dataframe, either polars or pandas.

```python
def memory(df: pd.DataFrame | pl.DataFrame) -> float:
    """
    Calculate the memory usage of a DataFrame in megabytes (MB).

    This function supports both pandas DataFrame and polars DataFrame.

    Parameters:
    df (pd.DataFrame | pl.DataFrame): The input DataFrame whose memory usage is to be calculated.

    Returns:
    float: The memory usage of the DataFrame in megabytes (MB).

    Example:
    >>> import pandas as pd
    >>> import polars as pl
    >>> df_pandas = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
    >>> df_polars = pl.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
    >>> memory(df_pandas) # TODO : this is also problematic as a doctest
    0.000124
    >>> memory(df_polars)
    0.000124
    """
    if isinstance(df, pd.DataFrame):
        mem = df.memory_usage(deep=True).sum()
    elif isinstance(df, pl.DataFrame):
        mem = df.estimated_size()

    return mem / 1024**2
```

### Suggest a solution if possible.

I would like something in narwhals

```python
def memory(df: IntoFrameT) -> float:
    ...
    return size
```

That I could safely use with any supported type of DataFrame.

### Additional information that may help us understand your needs.

I know a lot of these libraries use Arrow format under the hood, so the memory gap between them is probably negligible. Still, it would be nice to have such a function so that I don't have to find the proper method (under different names) in different libraries.

**Comment by MarcoGorelli** [comment]
Thanks for the request

https://narwhals-dev.github.io/narwhals/api-reference/dataframe/#narwhals.dataframe.DataFrame.estimated_size

Does this work for you?

**Comment by paulduf** [comment]
Thanks, this is exactly what I was looking for ! I used narwhals 1.14.2 and looks it was implemented in a later version. I just close this issue then.
