### ISSUE TITLE
test: test group_by(...).agg(nw.col(...).var())

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1586]
Realised today that we don't have any tests for `df.group_by(...).agg(nw.col(...).var())`. Let's add one!

This should be very similar to the std one:

https://github.com/narwhals-dev/narwhals/blob/44cf9e39840f85901d39f8f44b24b6ea39050c3b/tests/group_by_test.py#L130-L136

You could even just parametrise over the aggregation function and `expected`. Or just add it below

**Comment by Dhanunjaya-Elluri** [comment]
Hi @MarcoGorelli, I took this issue to work on, but I observed the `Expr` class does not have `var()` method.

**Comment by MarcoGorelli** [comment]
Ah in that case we first need to implement Expr.var and Series.var, thanks

**Comment by Dhanunjaya-Elluri** [comment]
Can I take up this to implement? Seems like a good feature to implement!

**Comment by MarcoGorelli** [comment]
sure thanks!

**Comment by Dhanunjaya-Elluri** [comment]
Hi @MarcoGorelli, I have introduced `var` method here #1603. Please review it and let me know if any changes is necessary.
