### ISSUE TITLE
Docs: IntoDataFrameT and IntoSeriesT may need a small correction

### ISSUE THREAD

**Issue by DeaMariaLeon** [narwhals-dev/narwhals#1590]
[IntoSeriesT](https://narwhals-dev.github.io/narwhals/api-reference/typing/#narwhals.typing.IntoSeriesT:~:text=Use%20this%20if%20your-,function%20accepts%20a%20function,-which%20can%20be%20converted%20to%20nw.Series) says "Use this if your function accepts a function".. should it be "your function accepts an object"? 

Same with [IntoDataFrameT](https://narwhals-dev.github.io/narwhals/api-reference/typing/#narwhals.typing.IntoDataFrameT:~:text=to%20Narwhals%20DataFrame.-,Use%20this%20if%20your%20function%20accepts%20a%20function,-which%20can%20be)

**Comment by MarcoGorelli** [comment]
yup, thanks!
