### ISSUE TITLE
docs/test: add tea-tasting to "used by" and to downstream ci tests

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1592]
https://github.com/e10v/tea-tasting have started using Narwhals, and are doing some pretty nice things with it! https://github.com/e10v/tea-tasting/pull/102

We should add them to the README, as well as to the downstream tests https://github.com/narwhals-dev/narwhals/blob/main/.github/workflows/downstream_tests.yml

**Comment by e10v** [comment]
> We should add them to the README

It's already done: https://github.com/narwhals-dev/narwhals/pull/1593

I've also seen your [suggestion](https://github.com/narwhals-dev/narwhals/pull/1593#pullrequestreview-2504256771) to add tea-tasting to downstream tests. The minor issue is that tea-tasting test dependencies are [specified](https://github.com/e10v/tea-tasting/blob/077626dfe44940f2cb2360a9d1d60d5949afdbbd/pyproject.toml#L56) in the PDM section of pyproject. And I see that you prefer uv in the downstream tests.

**Comment by MarcoGorelli** [comment]
Thanks for taking a look! Sure, we can use pdm for this Ci job, no issue
