### ISSUE TITLE
enh: support `nw.col('a').shift(n).over('b')`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1609]
We now support cumulative operations in `over` for pandas and Polars

We should do the same for `shift`, as pandas also supports that. One challenge will be figuring out how to pass the argument down, but it should be doable

cc @ClaudioSalvatoreArcidiacono in case this interests you

**Comment by ClaudioSalvatoreArcidiacono** [comment]
Hey @MarcoGorelli thanks for pining me on this issue. I gave it a go yesterday evening, let me know what do you think about it.
