### ISSUE TITLE
ci: test that minimum versions job actually installs minimum versions (and same for other CI jobs)

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1615]
Here we install some minimum versions

https://github.com/narwhals-dev/narwhals/blob/919f2e5663a343d8491be9255d5dcf45161c9130/.github/workflows/extremes.yml#L27-L28

Here we display the installed versions: https://github.com/narwhals-dev/narwhals/blob/919f2e5663a343d8491be9255d5dcf45161c9130/.github/workflows/extremes.yml#L34-L35

Can we had a check to assert that the minimum versions that got installed? e.g. that `pyarrow==11` actually shows up, as opposed to say "pyarrow==17" which some other dependency might have upgraded?

**Comment by MarcoGorelli** [comment]
https://github.com/narwhals-dev/narwhals/pull/1617 addresses this for the minimum versions job, we should probably do it for the others too

**Comment by DeaMariaLeon** [comment]
I should have made it more clear that I was working on this. 
Anyway, I was also experimenting on having a "reusable job" to avoid repeating the Assert dependencies. One can avoid repeating oneself, but the code gets longer.
