### ISSUE TITLE
[Enh]: Adding a series as a new column to a dataframe

### ISSUE THREAD

**Issue by MathiasHolmstrom** [narwhals-dev/narwhals#1618]
Say I have a list of values and I want to create a new column using that list of values. In polars this can be done:
```

import polars as pl

df = pl.DataFrame(
    {"player": ["a", "b", "a", "c", "b", "a"], "value": [10, 20, 15, 5, 30, 25]}
)

list_a = [1, 0, 1, 0, 0, 1]

new_df = df.with_columns(
            pl.Series(name="new_column",values=list_a)
        )
```

However, I am struggling to figure out how to do this in Narwhals. The nw.Series works differently. Reading the documentation I see     

> This class is not meant to be instantiated directly - instead, use
>     `narwhals.from_native`, making sure to pass `allow_series=True` or
>     `series_only=True`.

But I am not exactly sure how to use that information to solve my issue. 

### Suggest a solution if possible.

I think it would be nice if it could work similarly to polars: 

```
import narwhals as nw
from narwhals.typing import FrameT

@nw.narwhalify
def add_np_array(df: FrameT) -> FrameT:
    return df.with_columns(
            nw.Series("new_column",[1, 0, 1, 0, 0, 1])
        )

new_df = add_np_array(df)
```
Although I appreciate any suggestion on how to solve my issue.

**Comment by FBruzzesi** [comment]
Hey @MathiasHolmstrom, thanks for raising this issue. 

You are correct, narwhals Series should not be used directly.

Depending on your native series type you can either use [`from_native(..., series_only=True)`](https://narwhals-dev.github.io/narwhals/api-reference/narwhals/#narwhals.from_native) or  [`new_series`](https://narwhals-dev.github.io/narwhals/api-reference/narwhals/#narwhals.new_series).

Here is example to show both together:

```py
import narwhals as nw
import pandas as pd
import polars as pl

def func(df_native, s_native, lst):
    return (
        nw.from_native(df_native, eager_only=True)
        .with_columns(
            x1 = nw.from_native(s_native, series_only=True),
            x2 = nw.new_series(
                name="x2",
                values=lst,
                native_namespace=nw.get_native_namespace(df_native)
            )
        )
    ).to_native()


func(pd.DataFrame(data), pd.Series(["x", "y", "z"]), [-1, 0, 1])
   a x1  x2
0  1  x  -1
1  2  y   0
2  3  z   1

func(pl.DataFrame(data), pl.Series(["x", "y", "z"]), [-1, 0, 1])
shape: (3, 3)
┌─────┬─────┬─────┐
│ a   ┆ x1  ┆ x2  │
│ --- ┆ --- ┆ --- │
│ i64 ┆ str ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ x   ┆ -1  │
│ 2   ┆ y   ┆ 0   │
│ 3   ┆ z   ┆ 1   │
└─────┴─────┴─────┘
```

**Comment by MarcoGorelli** [comment]
thanks for the report - yeah we should definitely mention `nw.new_series` there in the docs for `nw.Series`
