### ISSUE TITLE
[Enh]: Adding .explode expression

### ISSUE THREAD

**Issue by MathiasHolmstrom** [narwhals-dev/narwhals#1632]
I have some situations where I want to transform my dataframe into a long format where I have a column that contains a list of values (within each row). 

 Both Polars and Pandas have a .explode expression that allows me to do so. To my knowledge Narwhals does not? 

An example:
```

import polars as pl

df = pl.DataFrame(
    {
        "value": [["1", "2"], ["1", "2"]],
        "number": ["1", "2"]
    }
)
df_exploded = df.explode(["value"])
```

Is this something that could be added or is there another alternative to accomplish the same?

**Comment by MarcoGorelli** [comment]
Hi @MathiasHolmstrom 

Yup there's a pr open - fancy giving it a review to see if it fits your needs?

**Comment by MathiasHolmstrom** [comment]
Ah sorry only searched the issues. Didn't check the PR. Looking forward to it.
