### ISSUE TITLE
wrong argument in Expr.filter and Series.filter - "other" instead of "*predicates"

### ISSUE THREAD

**Issue by anopsy** [narwhals-dev/narwhals#197]
I'm working on the docstring for Expr.filter() but I noticed that the name of the argument suggests it accepts "other" df/series.
It's also the case for Series.filter()
Dataframe.filter() has *predicates as an argument and so does Expr.filter() in polars.
Should it be that way or should it be corrected?

**Comment by FBruzzesi** [comment]
That's about right. In polars `Expr`s support filtering by other expr/series:

```py
import polars as pl

frame = pl.DataFrame({
    "a": [1, 2, 3, 1],
    "b": ["a", "a", "b", "c"]
})

frame.select(pl.col("a").filter(pl.col("b")=="a").mean().alias("a_mean_filtered"), pl.col("a").mean()
```

```terminal
shape: (1, 2)
┌─────────────────┬──────┐
│ a_mean_filtered ┆ a    │
│ ---             ┆ ---  │
│ f64             ┆ f64  │
╞═════════════════╪══════╡
│ 1.5             ┆ 1.75 │
└─────────────────┴──────┘
```

**Comment by DeaMariaLeon** [comment]
>I'm working on the docstring for Expr.filter()
Thanks @anopsy, but there is an open PR for that already https://github.com/narwhals-dev/narwhals/pull/196

**Comment by anopsy** [comment]
Okay, cool to know. Just wondering why the polars' Expr.filter() doesn't have "other" as an argument
![image](https://github.com/narwhals-dev/narwhals/assets/74981211/2bf6aa9f-cd9a-460a-a2e0-c76010be3e1d)

**Comment by anopsy** [comment]
> Thanks @anopsy, but there is an open PR for that already #196
Yes, I noticed after opening this issue

**Comment by MarcoGorelli** [comment]
hey!

> Okay, cool to know. Just wondering why the polars' Expr.filter() doesn't have "other" as an argument

I think I just named it wrong, and it should be called `predicates` (like it is in Polars)
