### ISSUE TITLE
Add plotting tutorial

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#201]
Currently, we have one complete example in which we create a standard scaler: https://narwhals-dev.github.io/narwhals/basics/complete_example/

It would be nice to add a second example, in which we make a plot of some kind. I don't know what exactly, feel free to let your imagination run wild. But the resulting plot must be pretty and colourful

If anyone wants to add a second complete example, that'd be great

then, we could:
- rename "complete example" to "Complete Example I: scikit-learn-like transformer"
- add "Complete Example II: plotting function"

**Comment by TylerEnglish** [comment]
I’ll work on this

**Comment by ChristianLG2** [comment]
@MarcoGorelli Should we only add the code along a png example it in the documentation or should we add it somewhere else? 
(Working with Benji on this)

**Comment by MarcoGorelli** [comment]
you might be able to get the code to generate the plot, not sure. otherwise exporting a png sounds fine, thanks!

**Comment by MarcoGorelli** [comment]
You'll probably want to add a file `docs/basics/plotting.md`

then, in `mkdocs.yml`, add that file to "`Tutorial`", so it shows:
```
    - basics/complete_example.md
    - basics/plotting.md
```

**Comment by MarcoGorelli** [comment]
you might also want to install https://pypi.org/project/mkdocs-matplotlib/

**Comment by mistShard** [comment]
### Bar plot

As I worked on the bar plot (using matplotlib), I wrote the following code attempting to use the ouput of `nw.from_native()` in the same way that a Pandas or Polars dataframe would be used:

```python
import narwhals as nw
import matplotlib.pyplot as plt
import pandas as pd
import polars as pl

data2 = {'Player': ['David De Gea', 'Paul Pogba', 'Edinson Cavani', 'Anthony Martial', 'Marcus Rashford', 'Cristiano Ronaldo'], 'Annual Salary': [19500000, 15080000, 13000000, 13000000, 10400000, 26800000]}

pd_df = pl.DataFrame(data2)

def plot_bar(df_any):
    df = nw.from_native(df_any)

    # Create the bar plot
    plt.figure(figsize=(10, 6))
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
    plt.bar(df['Player'], df['Annual Salary'].to_numpy(), color=colors, width=0.8)
```
 Note that using a Pandas or Polars dataframe produced the desired result, but the output of `nw.from_native()` threw the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[29], line 23
     20     plt.ylabel('Annual Salary (USD)')
     21     plt.title('Player Annual Salaries')
---> 23 plot_bar(pd_df)

Cell In[29], line 16
     14 plt.figure(figsize=(10, 6))
     15 colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
---> 16 plt.bar(df['Player'], df['Annual Salary'].to_numpy(), color=colors, width=0.8)
     18 # Add labels and title
     19 plt.xlabel('Player')

File c:\Users\hp\Documents\Work\OpenTeams\narwhals\.venv\Lib\site-packages\matplotlib\pyplot.py:2870, in bar(x, height, width, bottom, align, data, **kwargs)
   2859 @_copy_docstring_and_deprecators(Axes.bar)
   2860 def bar(
   2861     x: float | ArrayLike,
   (...)
   2868     **kwargs,
   2869 ) -> BarContainer:
-> 2870     return gca().bar(
   2871         x,
   2872         height,
   2873         width=width,
...
File c:\Users\hp\Documents\Work\OpenTeams\narwhals\narwhals\series.py:79, in Series.__array__(self, *args, **kwargs)
     78 def __array__(self, *args: Any, **kwargs: Any) -> np.ndarray:
---> 79     return self._series.to_numpy(*args, **kwargs)

TypeError: Series.to_numpy() takes 1 positional argument but 2 were given
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
```
I asked @MarcoGorelli for suggestions and he suggested that I alter the code to include `.to_numpy()` in the last line of code. The code became: `plt.bar(df['Player'].to_numpy(), df['Annual Salary'].to_numpy(), color=colors, width=0.8)`. This worked but I am not sure why it did.

**Comment by ChristianLG2** [comment]
@mistShard It worked because the `'plt.bar'` did not handle the custom series directly there were too many arguments so I think by converting the `df['player']` & `df[Annual Salary']` you made sure that the inputs are standardized so the `'plt.bar'` can handle them

**Comment by CLWilliam** [comment]
dibs! 👋🏾

**Comment by MarcoGorelli** [comment]
Going to close this due to lack of activity

I think this is my fault for not having defined the task clearly enough, thanks all sorry about this
