### ISSUE TITLE
Add docstrings for top-level methods

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#214]
Similar to https://github.com/narwhals-dev/narwhals/issues/71, please read the instructions there

But this time, we need to target the methods in:
https://narwhals-dev.github.io/narwhals/api-reference/narwhals/

**Comment by brentomagic** [comment]
i'll pick `len`, `max`, `mean`, `min`, and `sum`.

**Comment by MarcoGorelli** [comment]
looks like this is completed, thanks all!
