### ISSUE TITLE
Make nice release notes

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#239]
Can we auto-generate release notes based on PR titles? Polars does this and it's quite nice

**Comment by DeaMariaLeon** [comment]
Yes we can!

**Comment by DeaMariaLeon** [comment]
Polars use https://github.com/marketplace/actions/release-drafter

**Comment by DeaMariaLeon** [comment]
I'm working on this

**Comment by MarcoGorelli** [comment]
i think this is done, thanks Dea!
