### ISSUE TITLE
[Enh]: add conda as installation method

### ISSUE THREAD

**Issue by rpanai** [narwhals-dev/narwhals#249]
### Please describe the purpose of the new feature or describe the problem to solve.

It's possible to use conda as installation method. Is it possible to add this readme? [https://anaconda.org/conda-forge/narwhals](https://anaconda.org/conda-forge/narwhals)

### Would you want to open a pull request?

None

**Comment by MarcoGorelli** [comment]
thanks @rpanai for the request - does `conda install -c conda-forge narwhals` work? is that all that needs documenting?

**Comment by rpanai** [comment]
Hi @MarcoGorelli, yes it is.
