### ISSUE TITLE
[Bug]: pandas cast not working

### ISSUE THREAD

**Issue by GRcharles** [narwhals-dev/narwhals#253]
### Describe the bug

import polars as pl
import pandas as pd
df_polars = pl.DataFrame({'a': [1]})
nw.from_native(df_polars).select(nw.col("a").cast(nw.String) + "hi")

df_pandas = pd.DataFrame({'a': [1]})
nw.from_native(df_pandas).select(nw.col("a").cast(nw.String) + "hi")

polars succeeds, pandas fails with TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Steps or code to reproduce the bug

see description

### Expected results

it works as polars works

### Actual results

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Versions

```shell
narwhals==0.9.1
pandas==1.5.3
polars==0.20.26
```

**Comment by MarcoGorelli** [comment]
thanks @GRcharles for the report!

**Comment by MarcoGorelli** [comment]
This should be fixed in version 0.9.2, thanks again for your excellent bug report 🙏
