### ISSUE TITLE
RFC Perfect backwards compatibility policy

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#259]
Curious to hear thoughts on this one - especially from @baggiponte 

Narwhals follows a strict subset of the Polars API. What happens if/when some part of this subset gets changed in Polars itself?

For example:
- pre 1.0, Polars coalesces overlapping columns in left joins by default
- post 1.0, it won't by default

So, what do we do in Narwhals? I'd suggest allowing people to specify which API version they want to follow in `pyproject.toml`, e.g.:
```toml
[tool.narwhals]
api_version = "0.20"
```

Then:
- if somebody specifies `api_version = "0.20"` in pyproject.toml, then we promise to keep giving them the pre 1.0 behaviour indefinitely (coalesce by default in left joins)
- if somebody specifies `api_version = "1.0"` in pyproject.toml (or if they don't specify it), then we give them the post 1.0 Polars behaviour (don't coalesce by default in left joins)

The idea is that if you implement your library using Narwhals, then so long as you specify an `api_version` in `pyproject.toml`, then your code should preserve the same behaviour indefinitely. You may occasionally need to bump your minimum Narwhals package version (so we can deal with working around upstream changes in pandas/Polars/etc), but you should never need to rewrite your dataframe logic, it'll be perfectly backwards-compatible.

---

Very keen to also get @FBruzzesi and @koaning 's take on this, as consumers. Would you appreciate / be open to specifying a Narwhals `api_version` in your `pyproject.toml`, in exchange for the promise that the Narwhals API you use won't change?

---

So long as we stick to fundamental dataframe operations, and a strict subset of Polars (rather than trying to reimplement _everything_...) then I think this should be doable!

**Comment by koaning** [comment]
That can totally work for me, but I am not 100% sure if my tools would really suffer that much from the problems that you describe specifically. A lot of my transformations are stateless things.

**Comment by FBruzzesi** [comment]
From a narwhals user perspective I think this is ideal scenario, leading to minimal/no changes.

I am mostly thinking and concerned  about all the issues with narwhals internals rather than the benefits of this multiple polars api version support. Here a few that comes to mind:

- Behaviour changes: it may be some manual effort but fairly straightforward to deal with when one know which version to support.
- Methods renaming and/or deprecation: same as above
- Keyword renaming and/or deprecation: I noticed that it is happening quite a bit now, before the 1.0 release. This feels significantly harder to deal with in my opinion.

On a similar consideration, how are pandas-like changes dealt with internally to be mapped to the same result? Is there any such situation?

**Comment by MarcoGorelli** [comment]
Yeah we already have to do this for some older pandas versions:

https://github.com/narwhals-dev/narwhals/blob/fcd7292dc659cb9adf4bbd6309a68b9492ace014/narwhals/_pandas_like/group_by.py#L164-L167

Most of the Polars renamings deprecations happened for methods a bit on the fringe rather than the fundamental ones - but still, even then, we have to do deal with it sometimes:

https://github.com/narwhals-dev/narwhals/blob/509c370040ba9a00244688184c198163dd2daa5c/narwhals/dataframe.py#L93-L102

> This feels significantly harder to deal with in my opinion.

true, but I think we can manage

> From a narwhals user perspective I think this is ideal scenario, leading to minimal/no changes.

glad to read this 😄 going to see how hard it is to make this happen then, because API changes in pandas/polars do seem to be a major source of headaches for people trying to build tools on top of them

**Comment by koaning** [comment]
> I think it might still affect even stateless things - suppose for example that Polars renamed shift to lag. scikit-lego uses nw.col(...).shift, so if we were to follow Polars in Narwhals and also rename it, we'd break your code

Fair! But still, the proposed solution sounds totally fine to me. 

The only awkward thing that comes to mind is if there is a conflicting dependency. Say, scikit-playtime uses v20 and scikit-lego uses v21. I don't know how realistic this scenario is, but I might imagine a headacke happening here. I don't think there's a way to have two narwhals versions in a single venv.

**Comment by MarcoGorelli** [comment]
I think that could still be fine - for code called from scikit-playtime, Narwhals would use the v20 API, and for code called from scikit-lego, it would use the v21 API

(side-note, and I know it's not the point of your comment, but there won't be a v0.20, because the next Polars version is 1.0! 🥳 🍾 🌶️ )

**Comment by glemaitre** [comment]
Just jumping in the discussion ;).

Does having the info only in the `pyproject.toml` and thus metadata of the package kind of brittle: is there some settings that this info can be completely overlooked depending on the way the package is installed?

> `nw = StableNarwhals('0.20.0')`

So here the solution is more internal to the source code and thus more explicit. In scikit-learn, it makes me think about the `config_context` or the `set_config` that will set some global setting.

```python
with nw.config_context(api_version="0.20"):
    def func_1(df_any):
        ...
```

or without a context manager:

```python
nw.set_config(api_version="0.20")

def func_1(df_any):
    ...
```

I can imagine a third-party library to call the `set_config` into the `my_project/__init__.py` to set the api version.

**Comment by baggiponte** [comment]
I'm late to the party! I basically agree with Guillaume. While it's cool to have the `StableAPI` (though I'd like to put forward the motion to call it `Narwhalificator`), I think a global config that can be used as a decorator/context manager makes sense. It's low effort and can be used locally in an efficient manner. Also it does not force you to import the `nw` object you created somewhere in your library.

**Comment by MarcoGorelli** [comment]
Thanks @baggiponte ! I also like the look of just putting
```python
nw.set_config(api_version='0.20')
```
in `skbeer/__init__.py`, I just don't know how that works in practice. How would you implement this, so that the `api_version` that's set in `skbeer/__init__.py` only takes effect for calls to Narwhals made from within `skbeer`?

**Comment by baggiponte** [comment]
> It needs to be possible that:
> 
> * `skbeer` uses Narwhals with api_version 0.20
> * `skwine` uses Narwhals with api_version 1.0
> * a user has both installed, and nothing breaks

That's something I haven't considered! @glemaitre how does it work with sklearn?

**Comment by glemaitre** [comment]
> @glemaitre how does it work with sklearn?

We don't implement such thing so I did not think about the problem :)

**Comment by glemaitre** [comment]
> a  user has both installed, and nothing breaks

So somehow, you want to register the `api_version` to a package level. The only thing that I can think of is to have a global dict, where you either use the default or then register a `my_package_api_version` to not overwrite.

But devil is in the details, maybe implementing this is just to much of a spaghetti code.

**Comment by MarcoGorelli** [comment]
Thanks everyone for your inputs 🙏 

I've tried implementing this in https://github.com/narwhals-dev/narwhals/pull/331 . It's not finished, but it works well enough that I can test it out in scikit-lego and see what the impact is

Here is what the diff looks like (all tests pass, and this is backwards-compatible - you have the _option_ to use `narwhals.StableAPI`, but you don't have to, you can just `import narwhals as nw` and pray for the best):
```diff
diff --git a/sklego/linear_model.py b/sklego/linear_model.py
index 99f689b..cc896cc 100644
--- a/sklego/linear_model.py
+++ b/sklego/linear_model.py
@@ -9,7 +9,7 @@ from abc import ABC, abstractmethod
 from inspect import signature
 from warnings import warn
 
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 from scipy.optimize import minimize
 from scipy.special._ufuncs import expit
diff --git a/sklego/meta/_grouped_utils.py b/sklego/meta/_grouped_utils.py
index 97180ab..a6657c9 100644
--- a/sklego/meta/_grouped_utils.py
+++ b/sklego/meta/_grouped_utils.py
@@ -2,7 +2,7 @@ from __future__ import annotations
 
 from typing import List
 
-import narwhals as nw
+from sklego._narwhals import nw
 import pandas as pd
 from scipy.sparse import issparse
 from sklearn.utils import check_array
diff --git a/sklego/meta/_shrinkage_utils.py b/sklego/meta/_shrinkage_utils.py
index 0c82bf2..0398af4 100644
--- a/sklego/meta/_shrinkage_utils.py
+++ b/sklego/meta/_shrinkage_utils.py
@@ -1,6 +1,6 @@
 from functools import partial
 
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 from sklearn.utils.validation import check_is_fitted
 
diff --git a/sklego/meta/grouped_predictor.py b/sklego/meta/grouped_predictor.py
index 1cf3770..ef0941a 100644
--- a/sklego/meta/grouped_predictor.py
+++ b/sklego/meta/grouped_predictor.py
@@ -1,7 +1,7 @@
 from copy import deepcopy
 from typing import List, Union
 
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 import pandas as pd
 from sklearn import clone
diff --git a/sklego/meta/grouped_transformer.py b/sklego/meta/grouped_transformer.py
index 0a731b2..1a77818 100644
--- a/sklego/meta/grouped_transformer.py
+++ b/sklego/meta/grouped_transformer.py
@@ -1,6 +1,6 @@
 from typing import Union
 
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 from sklearn.base import BaseEstimator, MetaEstimatorMixin, TransformerMixin, clone
 from sklearn.utils.validation import check_is_fitted
diff --git a/sklego/meta/hierarchical_predictor.py b/sklego/meta/hierarchical_predictor.py
index 01f9a51..8096707 100644
--- a/sklego/meta/hierarchical_predictor.py
+++ b/sklego/meta/hierarchical_predictor.py
@@ -1,6 +1,6 @@
 from warnings import warn
 
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 import pandas as pd
 from joblib import Parallel, delayed
diff --git a/sklego/meta/regression_outlier_detector.py b/sklego/meta/regression_outlier_detector.py
index 7ba2230..9ecb0e7 100644
--- a/sklego/meta/regression_outlier_detector.py
+++ b/sklego/meta/regression_outlier_detector.py
@@ -1,4 +1,4 @@
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 from sklearn import clone
 from sklearn.base import BaseEstimator, OutlierMixin
diff --git a/sklego/model_selection.py b/sklego/model_selection.py
index edc8f86..74df119 100644
--- a/sklego/model_selection.py
+++ b/sklego/model_selection.py
@@ -3,7 +3,7 @@ from datetime import timedelta
 from itertools import combinations
 from warnings import warn
 
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 import pandas as pd
 from sklearn.exceptions import NotFittedError
diff --git a/sklego/pandas_utils.py b/sklego/pandas_utils.py
index e78da98..02ee895 100644
--- a/sklego/pandas_utils.py
+++ b/sklego/pandas_utils.py
@@ -2,7 +2,7 @@ import datetime as dt
 import inspect
 from functools import partial, wraps
 
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 from scipy.ndimage import shift
 
diff --git a/sklego/preprocessing/pandastransformers.py b/sklego/preprocessing/pandastransformers.py
index 1d516c3..bc68bfd 100644
--- a/sklego/preprocessing/pandastransformers.py
+++ b/sklego/preprocessing/pandastransformers.py
@@ -3,7 +3,7 @@ from __future__ import annotations
 import warnings
 from typing import Any
 
-import narwhals as nw
+from sklego._narwhals import nw
 from narwhals.dependencies import get_pandas
 from sklearn.base import BaseEstimator, TransformerMixin
 from sklearn.utils.validation import check_is_fitted
diff --git a/sklego/preprocessing/projections.py b/sklego/preprocessing/projections.py
index b99df9f..1d1ae2c 100644
--- a/sklego/preprocessing/projections.py
+++ b/sklego/preprocessing/projections.py
@@ -1,4 +1,4 @@
-import narwhals as nw
+from sklego._narwhals import nw
 import numpy as np
 from sklearn.base import BaseEstimator, TransformerMixin
 from sklearn.utils import check_array

```


I think this is fairly minimal, and gives a way to promise consumers: code you write today will keep working `x` years from now.

This is inspired by [Rust editions](https://doc.rust-lang.org/edition-guide/editions/), so there is a working precedent for doing this, just not (as far as I'm aware) in the Python space

Any feedback on the design? Would you use this? Does any part of it risk being confusing? 🙏

**Comment by jcheng5** [comment]
@MarcoGorelli Have you considered having different classes for the different editions? `StableAPIv1`, `StableAPIv2`...

Without that, I don't know how static types can reflect things like `cum_sum` in 1.0 becoming `cumulative_sum` in 2.0.

(Also, hello from the [Shiny](https://shiny.posit.co/py/) team--we're thinking about using Narwhals for our various dataframe related features!)

**Comment by MarcoGorelli** [comment]
Thanks @jcheng5 for your input! Indeed, static types are in issue in the proposal I'd written previously

Something I'm trying out is
```python
import narwhals.stable.v0_20 as nw
# import narwhals.stable.v1_0 as nw
```
in which things seem to be behaving a lot more nicely

Also, that's amazing that you're considering Narwhals for use in Shiny 🙏 ! Please do let me know if there's anything I can do on the Narwhals side that would make it easier for (e.g. any missing features you need?), and feel free to book time on https://calendly.com/marcogorelli if that would be easier over a call

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli Have you considered having different classes for the different editions? StableAPIv1, StableAPIv2...

Alright, this took some effort, but `narwhals.stable.v1_0` is now implemented in https://github.com/narwhals-dev/narwhals/pull/410

There's several check to ensure it stays up-to-date with the main namespace

I've also sneakily added `Expr._taxicab_norm`, so we can make as-realistic a test as possible that, in `narwhals.stable.v1_0`, we can rename it to `Expr._l1_norm` with this affecting the main namespace
