### ISSUE TITLE
[Enh]: get the dtype

### ISSUE THREAD

**Issue by koaning** [narwhals-dev/narwhals#260]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

For scikit-playtime I find myself hitting an issue where I kind of need to assume that a date is passed as a string in a dataframe. It works for now, but it'd be preferable for narwhals to be able to do the casting on behalf of the user if that is required.

With that in mind, it'd be nice to have access to the dtypes property on the dataframe/columns. I could be wrong but it seems like that is not implemented yet. Once I have that info I can do the casting with an if-statement in there somewhere.

### Please describe the purpose of the new feature or describe the problem to solve.

see above

### Suggest a solution if possible.

see above 

### If you have tried alternatives, please describe them below.

I could cast everything to a string automatically, but that feels wasteful.

### Would you want to open a pull request?

None

**Comment by MarcoGorelli** [comment]
hey sorry, just want to ask if you could provide further details please, as I _think_ the request is covered by `DataFrame.schema` and `Series.dtype`

**Comment by MarcoGorelli** [comment]
closing for now as I think this is covered, but if you provide more details, I'd be 110% happy to address this
