### ISSUE TITLE
Release Drafter follow up

### ISSUE THREAD

**Issue by DeaMariaLeon** [narwhals-dev/narwhals#263]
As a reminder, the release drafter classifies the pull requests based on their titles. The drafter is working, but we need to agree on how to handle those titles. 

If a PR's title is not correct, it won't be classified under the correct type.

Polars asks contributors [to start their PR with a conventional commit name](https://docs.pola.rs/development/contributing/#working-on-your-issue:~:text=Start%20your%20pull%20request%20title%20with%20a%20conventional%20commit%20tag.%20This%20helps%20us%20add%20your%20contribution%20to%20the%20right%20section%20of%20the%20changelog.%20We%20use%20the%20Angular%20convention.%20Scope%20can%20be%20rust%20and/or%20python%2C%20depending%20on%20your%20contribution.). And they use ~this library as well~: https://www.conventionalcommits.org/en/v1.0.0/#summary

We could do as Polars. Another way would be to modify the regular expressions on [.github/release-drafter.yml](https://github.com/narwhals-dev/narwhals/blob/main/.github/release-drafter.yml), to try to correct the classification. As I already did for the "documentation" label:

```
- label: documentation
    title:
      - '/(.*doc|.*docstring)/'
```

I would like to know what you prefer.

**Comment by FBruzzesi** [comment]
It is also possible for maintainers to modify the PR title before merging (that's the famous human in the loop 😂)
