### ISSUE TITLE
[Enh]: Add support for DataFrame.write_parquet

### ISSUE THREAD

**Issue by Priyansh121096** [narwhals-dev/narwhals#284]
### Please describe the purpose of the new feature or describe the problem to solve.

I have a library which lets users ingest a pandas dataframe to a datalake. The dataframe provided to the lib by the user is converted to a parquet file (with pyarrow) before putting it in an ETL pipeline. I'd like to let users ingest polars dataframes as well via the same library and would like to use narwhals for the implementation, if possible.

### Suggest a solution if possible.

For polars, `nw.DataFrame.write_parquet` would be the same as `pl.DataFrame.write_parquet`.
For pandas, `nw.DataFrame.write_parquet` would be `pd.DataFrame.to_parquet`.

### Would you want to open a pull request?

no

**Comment by MarcoGorelli** [comment]
hey @Priyansh121096 !

Seems like a good request to me! I think that reading data is probably out-of-scope for Narwhals - but writing, that should be in-scope

**Comment by MarcoGorelli** [comment]
this should be available in the new version, pls let us know if it doesn't work for you, thanks!
