### ISSUE TITLE
[Enh]: Add support for DataFrame.rows

### ISSUE THREAD

**Issue by Priyansh121096** [narwhals-dev/narwhals#285]
### Please describe the purpose of the new feature or describe the problem to solve.

I have a library which accepts a pandas dataframe and serializes it into a list of lists (`df.values.tolist()`) before processing it further. I would like to make the library work with polars dataframes as well and would like to use narwhals for the same.

### Suggest a solution if possible.

For polars, `nw.DataFrame.rows()` would be the same as `pl.DataFrame.rows()`.
For pandas, `nw.DataFrame.rows()` would be `pd.DataFrame.values.tolist()`.

### Would you want to open a pull request?

yes

**Comment by MarcoGorelli** [comment]
thanks @Priyansh121096 for the request! sure, open to this!

I think for pandas we might want to use https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples though

```python
In [12]: pl.DataFrame({'a': [1,2], 'b': [3., 4.]}).rows()
Out[12]: [(1, 3.0), (2, 4.0)]

In [13]: list(pd.DataFrame({'a': [1,2], 'b': [3., 4.]}).itertuples(index=False, name=None))
Out[13]: [(1, 3.0), (2, 4.0)]
```
else `.values` would upcast

**Comment by MarcoGorelli** [comment]
yes, of course, thanks! check `contributing.md` if you need help

**Comment by MarcoGorelli** [comment]
hey @Priyansh121096 - just wanted to ask how you were finding this, and if you appreciate any help

**Comment by Priyansh121096** [comment]
Hello @MarcoGorelli, thanks for reaching out. I have started the work on this today and should be raising a PR soon. I'll reach out if I have any questions.

**Comment by Priyansh121096** [comment]
@MarcoGorelli I've raised #317 for this

**Comment by MarcoGorelli** [comment]
I spoke to Polars devs about this today, and they said that if you need a list, it's actually more efficient to use `.rows` directly

So, sorry for my bad suggestion - I'll reopen this then, let's add `.rows` as well 💪

**Comment by Priyansh121096** [comment]
Sure @MarcoGorelli, I'll raise a PR for `.rows` then.

**Comment by Priyansh121096** [comment]
@MarcoGorelli raised #351 for `.rows`.
