### ISSUE TITLE
[Enh]: Arithmetic operations for DataFrame & Series

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#286]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

Arithmetic operations are not supported (yet)

### Please describe the purpose of the new feature or describe the problem to solve.

Adding to series or dataframe will result in `TypeError`:

```py
import polars as pl
import narwhals as nw

nw.from_native(pl.DataFrame({"a": [1,2,3]})) + 1
```
> TypeError: unsupported operand type(s) for +: 'DataFrame' and 'int'

```py
nw.from_native(pl.Series([1,2,3]), allow_series=True) + 1
```
> TypeError: unsupported operand type(s) for +: 'Series' and 'int'

### Suggest a solution if possible.

Is there a way to use the `Expr` implementation directly? i.e. the following has no issues:

```py
nw.from_native(pl.DataFrame({"a": [1,2,3]})).with_columns(a = nw.col("a") + 1)
```

### Would you want to open a pull request?

None

**Comment by MarcoGorelli** [comment]
hey - yeah seems like a reasonable request, thanks!

**Comment by MarcoGorelli** [comment]
For the first one, you can do `.with_columns(nw.all()+1)`. Is that enough?

Implementing the second one should just be a matter of doing
```diff
diff --git a/narwhals/series.py b/narwhals/series.py
index eced485..e3dac9a 100644
--- a/narwhals/series.py
+++ b/narwhals/series.py
@@ -1102,6 +1102,9 @@ class Series:
         """
         return self._series.to_pandas()
 
+    def __add__(self, other: object) -> Series:  # type: ignore[override]
+        return self._from_series(self._series.__add__(self._extract_native(other)))
+
```

**Comment by MarcoGorelli** [comment]
I've opened https://github.com/narwhals-dev/narwhals/pull/288 to add Series arithmetic

For DataFrame, does `nw.all()` work for you?

**Comment by FBruzzesi** [comment]
Thanks Marco, that's an incredible effort!  Time to go to a meetup and you already solved this! 🥳
