### ISSUE TITLE
[Enh]: Add local testing framework

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#292]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

It's an internal nice to have

### Please describe the purpose of the new feature or describe the problem to solve.

Using tox or nox for local testing can lead to less surprises when opening PRs

### If you have tried alternatives, please describe them below.

Manual local testing

### Would you want to open a pull request?

yes

### Additional information that may help us understand your needs.

Is this of any interest? If so, do we have preference/opinion on which framework to use?

**Comment by MarcoGorelli** [comment]
I'm too familiar with either, I usually just do `pytest tests --cov=narwhals`. Happy to try this out though!
