### ISSUE TITLE
[Enh]: Support for `how="cross" in DataFrame.join()

### ISSUE THREAD

**Issue by DeaMariaLeon** [narwhals-dev/narwhals#301]
### Please describe the purpose of the new feature or describe the problem to solve.

Needed for TPC-H query Q11. Issue https://github.com/narwhals-dev/narwhals/issues/282

### Would you want to open a pull request?

None

**Comment by FBruzzesi** [comment]
I took a quick look. [Polars docs](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join.html) say:

> Returns the Cartesian product of rows from both tables

and also experimentally it seems that join keys are just disregarded.
Is this correct?
