### ISSUE TITLE
[Enh]: DataFrame.collect_schema and LazyFrame.collect_schema

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#313]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

Polars 1.0 is about to come out, and it will have `collect_schema`. We should add it here too

https://docs.pola.rs/api/python/dev/reference/lazyframe/api/polars.LazyFrame.collect_schema.html#polars.LazyFrame.collect_schema

### Please describe the purpose of the new feature or describe the problem to solve.

Polars 1.0 compatibility

**Comment by mfonekpo** [comment]
I will work on this @MarcoGorelli

**Comment by mfonekpo** [comment]
Please can you give me some pointers on how to go about this? Thank you.

**Comment by MarcoGorelli** [comment]
thanks for your interest - I'd suggest focusing on https://github.com/narwhals-dev/narwhals/pull/312#pullrequestreview-2129724430 until that's finished

**Comment by FBruzzesi** [comment]
With polars 1.0, calling LazyFrame.columns seems to break CI ([proof](https://github.com/narwhals-dev/narwhals/actions/runs/9795456635/job/27047665344?pr=395)).
