### ISSUE TITLE
Extend `narwhalify` decorator

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#320]
As discussed in this PR https://github.com/narwhals-dev/narwhals/pull/266, we should probably extend `narwhalify` with extra capabilities

Maybe - only maybe - we should aim for it to be the primary way that people interact with Narwhals? Not totally sure on this one

**Comment by FBruzzesi** [comment]
It may be worth discussing a few strategy that we can have. I see the following:

1. (Try to) convert every argument to narwhals with `strict=False` flag (both in input and output)
2. Allow user to specify which arguments and output to convert to and back from narwhals.
    - Leaves more freedom to the user, if some very custom operation need to be performed.
3. Use type checks to convert dataframe/series only objects 

I personally prefer option 1., it is possibly opinionated but also a very clear promise that everything that can be converted, will be converted.

Extra: in each case we should check that the dataframe objects come with the same backend

WDYT?

**Comment by FBruzzesi** [comment]
[WIP attempt ](https://github.com/narwhals-dev/narwhals/compare/main...enh/extend-narwhalify) for 1. 

- Implementation is 90% there I would say
- Mypy needs some love
- Docs need to be updated
- Tests need to be updated
