### ISSUE TITLE
[bug]: `SeriesGroupBy` operations

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#326]
### Please describe the purpose of the new feature or describe the problem to solve.

Despite the implementation of `Expr` and `Series` [`.len()` method](#323), when used in a `group_by` context and pandas-like backend the operation fails to execute with the following downstream error:

> AttributeError: 'SeriesGroupBy' object has no attribute 'len'

This enters the intricacies of pandas grouped objects, which we didn't tackle (just yet).

Creating the issue to keep track of this

### If you have tried alternatives, please describe them below.

In this particular case `nw.col("foo").len()` can be replaced by `nw.len()`.

**Comment by MarcoGorelli** [comment]
thanks for spotting this - I'd say that it's a bug

reproducible example
```python
data = {'a': [1,1,2], 'b': [4,5,6]}
dfpd = pd.DataFrame(data)

df = nw.from_native(dfpd)
df.group_by('a').agg(nw.col('b').len())
```
