### ISSUE TITLE
DOCS: add docstring for `concat`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#337]
`concat` doesn't have a docstring yet https://narwhals-dev.github.io/narwhals/api-reference/narwhals/#narwhals.concat

Anyone fancy writing one?

**Comment by InessaPawson** [comment]
@MarcoGorelli I've started working on it here: https://github.com/narwhals-dev/narwhals/compare/main...InessaPawson:narwhals:docstring-concat. I will finalize it in a couple of days if that's ok.

**Comment by MarcoGorelli** [comment]
hi @InessaPawson , is this still active?

**Comment by Sherwin-14** [comment]
@MarcoGorelli Hey marc I would like to take this up, do you have any specific opinions?

**Comment by MarcoGorelli** [comment]
sure go ahead, thanks @Sherwin-14 ! check out other docstrings to see how it should be done

**Comment by InessaPawson** [comment]
This has been resolved with https://github.com/narwhals-dev/narwhals/pull/808/.
Thank you for getting it to the finish line, @Sherwin-14, @FBruzzesi , @MarcoGorelli !
