### ISSUE TITLE
[Enh]: Use a dependency manager for the project

### ISSUE THREAD

**Issue by ELC** [narwhals-dev/narwhals#339]
### Please describe the purpose of the new feature or describe the problem to solve.

It is common in the python ecosystem to use a library to handle dependencies, specially when dealing with heavy packages like the ones used in the data space.

The following are some of the most popular packages for this purpose:

![star-history-2024626 (1)](https://github.com/narwhals-dev/narwhals/assets/14986783/4fbae11e-1425-44a6-aa5f-0725ef8681e9)

My impressions:

- PDM: FastAPI migrated to this tool from poetry, it is indeed promising because of its support of most modern PEPs
- Poetry: most popular tool so far
- Pipenv: my personal favorite because it uses Pipfile and it is from Pypa org
- Uv: From the creators of Ruff, fastest growing library in this space
- Hatch: it is already used in this project as build backend but lacks support for locking dependencies

### Suggest a solution if possible.

My personal preference is to go with PDM or Pipenv.

UV seems promising but is too new to my taste at the moment and will be worth having a deeper look in a couple of month.

I would highly encourage against using mamba / conda since those are usually not used in enterprise apps plus there are licensing issues with the Anaconda license change a couple of years back.

**Comment by MarcoGorelli** [comment]
thanks for the suggestion - I think we don't need to lock dependencies here, because we're testing different versions of packages in CI

**Comment by ELC** [comment]
Since this has no direct dependencies, including a dependency manager will not impact builds and installs but may simplify local setup for dev dependencies.

If that is too much for this we can close this

**Comment by MarcoGorelli** [comment]
sure, let's close for now then, but thanks for the request!
