### ISSUE TITLE
feat: add `.cat.get_categories`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#342]
We should add `.cat.get_categories`, see https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.cat.get_categories.html, to Narwhals

**Comment by MarcoGorelli** [comment]
wait, we've already got this

and I added it, apparently

**Comment by FBruzzesi** [comment]
Negative overhead in issue tracker: make PR and feature first, add related issue later 😁
