### ISSUE TITLE
[Doc]: Fix Series.shift() and Series.diff()

### ISSUE THREAD

**Issue by DeaMariaLeon** [narwhals-dev/narwhals#352]
### What type of report is this?

Correction

### Please describe the issue.

The code block inside the Notes of `shift()`and `diff()` are supposed to have a python code block. This is not rendering correctly.

<img width="984" alt="Screenshot 2024-06-29 at 14 12 17" src="https://github.com/narwhals-dev/narwhals/assets/11835246/44ec3175-1239-4807-ac35-1353fc51f2fd">
62a-b5a0-6aa53f4f7772">
<img width="972" alt="Screenshot 2024-06-29 at 14 13 24" src="https://github.com/narwhals-dev/narwhals/assets/11835246/d3e681c3-c62e-4492-9d50-eed1e982910e">

**Comment by MarcoGorelli** [comment]
thanks for spotting this!
