### ISSUE TITLE
feat: Add missing methods to PyArrow backend

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#372]
Narwhals methods are generally available for pandas-like APIs and Polars

We should make sure that PyArrow table has the same amount of coverage. Nearly anything can be converted to PyArrow, so this would really be worth it.

The task here is:
1. Choose a method from the `MISSING` list in [`https://github.com/narwhals-dev/narwhals/blob/main/utils/check_backend_completeness.py#L14`](https://github.com/narwhals-dev/narwhals/blob/main/utils/check_backend_completeness.py#L14)
2. Implement that method in `narwhals/_arrow/dataframe.py` or `narwhals/_arrow/series.py`
3. Make sure that there are tests to cover the new function you've added
4. Once you've got 100% coverage and all tests pass, open a PR! 🙌 

It might be a good idea to leave a comment indicating which method(s) you're working on, so we don't duplicate work

**Comment by brentomagic** [comment]
i'll start with series.min.

**Comment by MarcoGorelli** [comment]
cool @brentomagic ! it might be good to first address part of https://github.com/narwhals-dev/narwhals/issues/401 so that there's a test for `Series.min` which uses `constructor_series`, so you can then swap out `constructor_series_with_pyarrow` in its place

or to start with a method where the tests already use `constructor_series`, such as `Series.to_frame`

**Comment by lucianosrp** [comment]
Just adding here that https://github.com/narwhals-dev/narwhals/pull/455 adds the StringNamespace in the PyArrow implementation (`narwhals/_arrow`)

**Comment by anopsy** [comment]
Hi there! If it's not already taken I'll work on   "Series.is_in", "Series.len"

**Comment by MarcoGorelli** [comment]
yeeesss @anopsy ! 🙌 !

**Comment by MarcoGorelli** [comment]
> Edit: Now I see, len is on the MISSING list, but there's already _ len _ in _arrow.series.py 🤔

yeah we need both, as `Expr.len()` is a (lazy) method, but Python requires us to return an integer from `__len__`

**Comment by FBruzzesi** [comment]
Not in the list but possible to support we have some dunder methods as well:

- [ ] `__rand__`
- [ ] `__ror__`
- [ ] `__radd__`
- [ ] `__rsub__`
- [ ] `__rmul__`
- [ ] `__rpow__`
- [ ] `__rmod__`
- [ ] `__truediv__`
- [ ] `__rtruediv__`
- [ ] `__floordiv__`
- [ ] `__rfloordiv__`

**Comment by MarcoGorelli** [comment]
I'm working on group-by

@mistShard could you take on `n_unique` please? it should be quite similar to https://github.com/narwhals-dev/narwhals/pull/457

**Comment by mistShard** [comment]
@MarcoGorelli I'll start on that

**Comment by FBruzzesi** [comment]
For general information: as we just merged #515, now when someone adds a new feature/method for arrow, in terms of testing it should be enough to remove the following block:

```py
if "pyarrow_table" in str(constructor_with_lazy):
    request.applymarker(pytest.mark.xfail)
```

Diff should look like:

```diff
- def test_concat_vertical(request: Any, constructor_with_lazy: Any) -> None:
-     if "pyarrow_table" in str(constructor_with_lazy):
-           request.applymarker(pytest.mark.xfail)
+ def test_concat_vertical(constructor_with_lazy: Any) -> None:
```

If the implemented feature passes the test but the test is still marked to fail, you should receive an error when running the test suite anyway. Example output from #525 before changing as suggested above:

> _________________________ test_concat_vertical[pyarrow_table_constructor] _________________________
> [XPASS(strict)]

**Comment by mfonekpo** [comment]
I will be picking up `Series.len` method. I hope nobody else is working on that?

**Comment by mfonekpo** [comment]
I will be picking up `Series.len` method. I hope nobody else is working on that.

**Comment by mfonekpo** [comment]
I will be picking up `Series.len` method. I hope nobody else is working on that.

**Comment by MarcoGorelli** [comment]
based on https://github.com/narwhals-dev/narwhals/issues/372#issuecomment-2225063542, @anopsy is working on it, could you please choose another one?

**Comment by mfonekpo** [comment]
I pick `Series.drop_nulls`

**Comment by lucianosrp** [comment]
I'm going for `Series.is_null`  🏃‍♂️

**Comment by brentomagic** [comment]
i'll look into `series.round`

**Comment by lucianosrp** [comment]
Doing:
 `__truediv__`
 `__rtruediv__`
 `__floordiv__`
 `__rfloordiv__`
 
 I think `__mod__` and  `__rmod__` is not doable with `pyarrow.compute` yet

**Comment by MarcoGorelli** [comment]
thanks @lucianosrp ! you may want to check the discussions in https://github.com/narwhals-dev/narwhals/pull/491 where we'd discussed truediv a bit

**Comment by anopsy** [comment]
I'll have Series. value_counts 🌊

**Comment by mistShard** [comment]
I'll be looking into `Series.unique`

**Comment by FBruzzesi** [comment]
I will try to address DataFrame `is_duplicated`, `is_unique` and `unique`

**Comment by mfonekpo** [comment]
I will work on `Series.round`

**Comment by MarcoGorelli** [comment]
@brentomagic has a PR open for that one

**Comment by FBruzzesi** [comment]
I am taking care of `Series.sort` and `Series.unique` as very useful for #575

**Comment by MarcoGorelli** [comment]
some top-level methods are also missing for arrow:
- `nw.min`
- `nw.max`
- some others

In terms of test coverage, it should be enough to find a case of `nw.col(...).min()` and change it to `nw.min(...)` and check it still passes

**Comment by FBruzzesi** [comment]
Considering the look of the [api completeness](https://narwhals-dev.github.io/narwhals/api-completeness/) doc section... great job everyone 🙌🏼🎉
