### ISSUE TITLE
[Enh]: Support for anti-join

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#374]
### Please describe the purpose of the new feature or describe the problem to solve.

Hands down one of my favorite feature 😂
The fact that polars has native support is really convenient

### Suggest a solution if possible.

It should look something like the following:

```py
(df
.merge(other, how='outer', indicator = True)
.loc[lambda t: t["_merge"]=="left_only"]
.drop("_merge", axis=1)
)
```

We can decide to name the indicator column with another non-default value

**Comment by MarcoGorelli** [comment]
yeesssss nice one
