### ISSUE TITLE
[Enh]: Support for `DataFrame.pivot`

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#392]
### Please describe the purpose of the new feature or describe the problem to solve.

_pivot_-al feature to add!

### Additional information that may help us understand your needs.

Challenges:
- Regarding StableAPI, polars pivot would bring the first challenge in supporting two different APIs [v1.0](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html) vs [v0.20](https://docs.pola.rs/api/python/version/0.20/reference/dataframe/api/polars.DataFrame.pivot.html) 
- I am not sure that pandas-like `pivot_table` does support all the `aggregate_function`s out of the box

**Comment by MarcoGorelli** [comment]
thanks for the request, agree it would be useful

> Regarding StableAPI, polars pivot would bring the first challenge in supporting two different APIs [v1.0](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html) vs [v0.20](https://docs.pola.rs/api/python/version/0.20/reference/dataframe/api/polars.DataFrame.pivot.html)

we don't need to worry about this, the idea behind the stable api is "if you write code, we won't break it" - we don't have pivot yet in Narwhals, so we don't need to introduce an old syntax. we can just add it to the v1.0 api

**Comment by FBruzzesi** [comment]
Closing this as not planned for now. It never appeared in any library integration we are considering so far and the closed PR showed how inconsistent it would be to have a coherent mapping between polars versions

**Comment by MarcoGorelli** [comment]
good decision - it's usually possible to reimplement pivot in terms of groupby anyway, see the last example from https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html

**Comment by MarcoGorelli** [comment]
looks like this would be useful to Nixtla https://github.com/Nixtla/hierarchicalforecast/pull/305

back in my data scientist days I was a huge fan of their work, they're awesome, I think we should prioritise this

**Comment by elephaint** [comment]
THanks for the nice words! Let me try the example, I already thought it should be possible with group_by but didn't figure it out today - the example should get me going.
