### ISSUE TITLE
[Enh]: Add support for dask

### ISSUE THREAD

**Issue by benrutter** [narwhals-dev/narwhals#396]
### Please describe the purpose of the new feature or describe the problem to solve.

Dask is a dataframe library built on top of pandas to allow distributed computation of dataframes (like pyspark for example). It's API is a strict subset of the pandas API so in theory integrating it would be feasible. I'd be really down for contributing / looking into how support might work, but wanted to check if it's within the scope/aims of Narwhals or if it's been considered before? (Can't see anything on the issue tracker so I guess no?)

### Suggest a solution if possible.

Potentially a lot of pandas code could be reused although I haven't looked in depth to say that which much confidence.

### Additional information that may help us understand your needs.

I'd love to put in some contributions if it's within scope, I'm pretty experienced with Dask (have made some minor constibutions to dask-dataframe) but not so much with Narwhals. Would be great to get sense of interest for this as a feature, I realise adding in support for a whole new dataframe library is a big undertaking.

**Comment by MarcoGorelli** [comment]
thanks @benrutter for the request! I'd opened an issue about it here https://github.com/narwhals-dev/narwhals/issues/272, but yours is more complete, so I'll close that one

**Comment by MarcoGorelli** [comment]
regarding scope - this is definitely a library we need to aim to support

we have a `narwhals/_pandas_like` folder, where there are implementations for pandas-like APIs (pandas, modin, cudf)

for contributing, a good place to start might be to add a dask dataframe constructor to

https://github.com/narwhals-dev/narwhals/blob/bce5efa11110227b538f77fa6865d8bf51a68ad9/tests/conftest.py#L34-L66

, then run the test suite, and let the error messages guide you as to what needs fixing. fancy giving this a go?

we also have a discord where you can ask questions whilst contributing if you like, check the readme for the link

**Comment by benrutter** [comment]
Would absolutely love to give this a go! I'll try to dive into it over the next few days 🙌

**Comment by MarcoGorelli** [comment]
Dask support is still absolutely welcome, I'll just close in favour of https://github.com/narwhals-dev/narwhals/issues/396

**Comment by benrutter** [comment]
I'm guessing you mean #566? (this one is #396) Probably a good call, I enjoyed playing around with what support for Dask might look like, but it felt like currently it adds a bunch maintenance difficulties where someone editing the Pandas stuff has to have a good understanding of Dask not to break that too!

**Comment by MarcoGorelli** [comment]
thanks Ben, that's right!

yeah I think we may need a separate `narwhals/_dask` folder unfortunately..

**Comment by benrutter** [comment]
No worries! I'll close off my PR for now but keep tinkering around with thingsin thw fork so that there's a good base for when lazy only is an option.
