### ISSUE TITLE
clean: factor out tests from `test_common.py`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#401]
A lot of tests are in this file: https://github.com/narwhals-dev/narwhals/blob/main/tests/frame/test_common.py

This has a couple of issues:
- it's harder to find tests for some specific functions
- the tests rely on global `df_pandas` / `df_polars` / etc. variables

I think we should factor these out into dedicated functions, in which the input is a dictionary, and we use the `constructor` fixture (which parametrises over the different libraries)

Then, if we want to test extra backends, we should just be able to add the new library to the `constructor` fixture

See https://github.com/narwhals-dev/narwhals/pull/400/files for an example of how to do this

Another example: https://github.com/narwhals-dev/narwhals/pull/416 (note that `constructor_with_pyarrow` might not necessarily work yet - try it, and if it doesn't, just use `constructor`)

**Comment by FBruzzesi** [comment]
It should not be hard, but there are still a few tests in [`series_only/test_common.py`](https://github.com/narwhals-dev/narwhals/blob/main/tests/series_only/test_common.py)
