### ISSUE TITLE
`narwhalify` decorator doesn't (and can't?) preserve types

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#425]
Here's an example:
```python
import polars as pl
import narwhals as nw
from narwhals.typing import IntoDataFrameT

df = pl.DataFrame({'a': [1,2,3]})

def func(df_any: IntoDataFrameT) -> IntoDataFrameT:
    df = nw.from_native(df_any, eager_only=True)
    return nw.to_native(df.select(b=nw.col('a')))

reveal_type(func(df))

@nw.narwhalify(strict=True)
def func_2(df: nw.DataFrame[IntoDataFrameT]) -> nw.DataFrame[IntoDataFrameT]:
    return df.select(b=nw.col('a'))

reveal_type(func_2(df))
```

This gives
```console
$ mypy f.py 
f.py:11: note: Revealed type is "polars.dataframe.frame.DataFrame"
f.py:17: note: Revealed type is "Any"
Success: no issues found in 1 source file
```

In the first case, mypy can infer that `df` is a `polars.DataFrame`. In the second case, it can't.

Due to this, I'd like to rollback recommending `narwhalify` in the docs. I think `narwhalify` is nice, but given that Narwhals is primarily aimed at library maintainers, I'd prefer to default to teaching the way which follows engineering best practices such as typing as much possible

**Comment by MarcoGorelli** [comment]
Having tried this out quickly:
- the docstrings are probably OK to use `narwhalify`, I'm not sure type hints belong in docstrings anyway
- the user guide should probably use type hints in most places?

**Comment by FBruzzesi** [comment]
I will try to take a look if something can be improved in `narwhalify` in order to preserve types
