### ISSUE TITLE
Refactor: factor out PolarsDataFrame

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#461]
The current structure is:

```
.
└── narwhals
    ├── _arrow
    ├── _pandas_like
    └── stable
```

and differences between different Polars versions are handled directly in `narwhals.dataframe.py` and `narwhals.series.py`. I think it'd be cleaner if there was an extra `_polars` directory, i.e.:
```
.
└── narwhals
    ├── _arrow
    ├── _pandas_like
    ├── _polars
    └── stable
```
and that differences between Polars versions could all be handled in there

We could probably then remove `_is_polars` and `_backend_version` from `narwhals.DataFrame`

**Comment by FBruzzesi** [comment]
Closed by #561
