### ISSUE TITLE
[Enh]: Determine if Narwhals series should be returned in PandasLIkeDataFrame to_dict method

### ISSUE THREAD

**Issue by ELC** [narwhals-dev/narwhals#466]
### Please describe the purpose of the new feature or describe the problem to solve.

See this [snippet](https://github.com/narwhals-dev/narwhals/blob/c904b102bd95dec026ce756cecfda15dabe71f41/narwhals/_pandas_like/dataframe.py#L411-L424)

```python
    def to_dict(self, *, as_series: bool = False) -> dict[str, Any]:
        from narwhals._pandas_like.series import PandasLikeSeries

        if as_series:
            # TODO(Unassigned): should this return narwhals series?
            return {
                col: PandasLikeSeries(
                    self._native_dataframe.loc[:, col],
                    implementation=self._implementation,
                    backend_version=self._backend_version,
                )
                for col in self.columns
            }
        return self._native_dataframe.to_dict(orient="list")  # type: ignore[no-any-return]
```

**Comment by FBruzzesi** [comment]
As we are _moving out_ of a narwhals object, I would like to put up for discussion even the possibility of returning the native series.

To me `PandasLikeSeries` feels like the worst we can return honestly. The reason being, from a consumer point of view:

- it is very clear how to deal with a native series
- we provide support for handling `nw.Series` (e.g. `nw.to_native(...)`)
- `PandasLikeSeries` on the other hand is internal only object - we never mention it in the docs and we don't explain how to get the native object out of it (although it is quite easy)

**Comment by MarcoGorelli** [comment]
it's only PandasLikeSeries here, one level above it gets converted to narwhals.Series (via `._from_compliant_series`), the user never sees the PandasLikeSeries

**Comment by MarcoGorelli** [comment]
>  I would like to put up for discussion even the possibility of returning the native series.

yeah...maybe that's simpler at the end of the day

**Comment by FBruzzesi** [comment]
> it's only PandasLikeSeries here, one level above it gets converted to narwhals.Series (via `._from_compliant_series`), the user never sees the PandasLikeSeries

Oooh now I see! But indeed is seems even less relevant as the dataframe already has all the contextual info about backend, version and so on?!
