### ISSUE TITLE
Fix autolabeler

### ISSUE THREAD

**Issue by DeaMariaLeon** [narwhals-dev/narwhals#490]
The [release-drafter](https://github.com/narwhals-dev/narwhals/blob/main/.github/release-drafter.yml) only looks for lowercase titles on new PRs. But even when the PRs have the right format, it's not working.

Needs investigation.

**Comment by DeaMariaLeon** [comment]
It looks like something changed for the  `GITHUB_TOKEN` (like a permit or something). 
This error seems like the action wasn't allowed to do its thing: https://github.com/narwhals-dev/narwhals/actions/runs/9898914239

**Comment by MarcoGorelli** [comment]
hey - it looks like it worked here https://github.com/narwhals-dev/narwhals/pull/496, and it a few others?

**Comment by MarcoGorelli** [comment]
I _think_ it needs to be in the right format to begin with, and that once someone's opened a PR, correcting the title later doesn't change labels?

**Comment by FBruzzesi** [comment]
A label is automatically generated if as Marco said the title has the "right" format to start with.
I wonder what happens if we add the label afterwards manually - if the drafter is based on that I image it would still pick it up?!

**Comment by DeaMariaLeon** [comment]
There is no action on merge for the autolabeler I think. 
Maybe we should add it. Also the regex could be improved. I could experiment on my toy project.

**Comment by DeaMariaLeon** [comment]
I can add a bit of regex. At least to accept when the word starts with uppercase. As in `^([B|b]uild)` for example.
WDYT?

**Comment by FBruzzesi** [comment]
I think it would lead to some less work from our side when a PR is opened/merged, but I don't want to end up discouraging people from contributing because the title doesn't pass a regex check 🤌🏼😂

**Comment by DeaMariaLeon** [comment]
Regex is already being used on the drafter, but it only checks for lowercase.  If the regex expression finds something, it labels the PR correctly. 

If we add the uppercase check, the drafter will label the PRs more often (starting with "Build" or with "build", for example). 
Nothing blocks, or will block, the contributor to open a PR with the wrong title.

**Comment by FBruzzesi** [comment]
Loud and clear! Thanks a lot for explaining the mechanism 😁 I definitly  support that

**Comment by DeaMariaLeon** [comment]
Working on this now
