### ISSUE TITLE
[Bug]: should `_create_native_series` return narwhals series?

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#505]
### Describe the bug

I was trying to increase coverage by adding a test that calls [`ArrowNamespace._create_native_series`](https://github.com/narwhals-dev/narwhals/blob/main/narwhals/_arrow/namespace.py#L87): such method is accessed in `_expression_parsing.py` module [`parse_into_expr` function](https://github.com/narwhals-dev/narwhals/blob/main/narwhals/_expression_parsing.py#L153), and deals with the case of receiving a numpy array.

The result is fed into `namespace._create_expr_from_series`, which from type hint seems to expect a narwhals Series (ArrowSeries, PandasLikeSeries, and so on).

So far for pandas it resulted in no issues - my assumption is because numpy arrays implements most of the methods of the Series, or at least those that it is been used in.

However this is not true for pyarrow array: as one can check by running the `all_horizontal` test in the branch I am working on ([link](https://github.com/narwhals-dev/narwhals/blob/enh/increae-test-coverage/tests/expr/all_horizontal_test.py#L10))

### Steps or code to reproduce the bug

```py
import numpy as np
import narwhals as nw
import pyarrow as pa
import pandas as pd

arr = np.array([False, False, True]
data = {"b": [False, True, True]}

df_pd = pd.DataFrame(data)
df_pa = pa.table(data)

@nw.narwhalify
def func(dframe):
    return dframe.select(all=nw.all_horizontal(arr, nw.col("b")))

func(df_pd) # no errors
func(df_pa) # AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute '__and__'. Did you mean: '__ne__'?
```

### Expected results

```py
pa.table({"all": [False, False, True]})
```

### Actual results

> AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute '__and__'. Did you mean: '__ne__'?

### Please run narwhals.show_version() and enter the output below.

```shell
Python dependencies:
     narwhals: 1.0.6
       pandas: 2.2.2
       polars: 1.0.0
         cudf: 
        modin: 0.31.0
      pyarrow: 16.1.0
        numpy: 2.0.0
```

**Comment by FBruzzesi** [comment]
Maybe a simpler case to reproduce:

```py
import numpy as np
import pyarrow as pa

import narwhals.stable.v1 as nw

df = nw.from_native(pa.table({"a": [1, 2]}))

(df
 .with_columns(b = np.array([0,1]))  # So far so good!
 .with_columns(c = nw.col("b")**2)  # AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute 'alias'
)
```

**Comment by MarcoGorelli** [comment]
thanks @FBruzzesi ! indeed, `_create_native_series` should actually be `_create_compliant_series` and return `ArrowSeries` in the arrow case

did you want to make a PR for this?
