### ISSUE TITLE
[Doc]: Page with table for supported features (by backend type)

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#521]
### What type of report is this?

Improvement

### Please describe the issue.

I can envision that a _table_ with supported features by backend could be handy for people coming to the project.

### If you have a suggestion on how it should be, add it below.

I can give it a try to make it programmatically by parsing the main classes methods. If someone has something similar already implemented feel free to take a look into this

**Comment by FBruzzesi** [comment]
Draft of the idea would be to have something which look like the following:

| Class | Method  | Polars | Pandas-like | Arrow | 
| ------| ----------| ------- | ------------ | ------- |
| DataFrame | `with_columns`  |  ✅ | ✅ | ✅ |
| DataFrame | `is_duplicated`  |  ✅ | ✅ | ❌ |

**Comment by MarcoGorelli** [comment]
this would be amazing!

**Comment by FBruzzesi** [comment]
Would that be too meta to use polars for data manipulation?
