### ISSUE TITLE
[Bug]: exception in documentation code snippet

### ISSUE THREAD

**Issue by jonmmease** [narwhals-dev/narwhals#529]
### Describe the bug

In the new levels section of the docs (https://narwhals-dev.github.io/narwhals/levels/), there is a `NameError` where there should be some example code:

<img width="774" alt="Screenshot 2024-07-15 at 3 07 07 PM" src="https://github.com/user-attachments/assets/1408eddc-659d-40d5-9b14-3507c815d7c3">

### Steps or code to reproduce the bug

visit https://narwhals-dev.github.io/narwhals/levels/

### Expected results

see example code

### Actual results

see exception

### Please run narwhals.show_version() and enter the output below.

```shell
docs visited at the creation time of this issue
```

**Comment by MarcoGorelli** [comment]
thanks for the report 🙏 ! this will be fixed as part of https://github.com/narwhals-dev/narwhals/pull/530
