### ISSUE TITLE
feat: `nw.from_dict`?

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#572]
In `formulaic` they do something like this:
- they have some dataframe `self.data`
- they then create a pandas dataframe from a dict

I _think_ we need a way to do the same here. For example:
```python
import numpy as np
import pandas as pd
import narwhals as nw
df = pd.DataFrame({'b': [1, 2]})
nw_df = nw.from_native(df, eager_only=True)

other = nw.from_dict({'a': [1,2,3]}, module=nw.get_native_namespace(nw_df))
```

So like this, you pass `nw_df.__native_namespace__()` as an argument in the `from_dict` call, and Narwhals knows to create a `nw.DataFrame` backed by the right object (here, a pandas dataframe)

I dunno. We don't have the ability to just create dicts from nothing, so we need to _slightly_ depart from the Polars signature, although the top-level Narwhals functions already depart from Polars anyway

anyone got a better API in mind?

---

one alternative which comes to mind:
```
other = nw.__compliant_namespace__().from_dict({'a': [1,2,3]})
```
which doesn't exactly thrill me

**Comment by FBruzzesi** [comment]
I like this the first one more:

> `other = nw.from_dict({'a': [1,2,3]}, module=nw.get_native_namespace(nw_df))`

as we can implement `nw.DataFrame.from_dict` ourselves, while

> `other = nw.__compliant_namespace__().from_dict({'a': [1,2,3]})`

would require that the native namespace has `from_dict` function which is not necessarily true (arrow has `pa.Table.from_pydict`).
