### ISSUE TITLE
Series.to_dummies

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#575]
Bit of a tricky one, but it's one that Formulaic use

Polars has `Series.to_dummies`, pandas `pd.get_dummies`, no big deal

🤔 need to figure out how to do it for PyArrow

**Comment by MarcoGorelli** [comment]
can we use this for pyarrow https://stackoverflow.com/a/29831596/4451315

**Comment by FBruzzesi** [comment]
I think it is slightly different. 

If converting to numpy, we can use some broadcasted comparison:

```py
arr = table["foo"].to_numpy()
pa.Table.from_arrays(*[arr[None, :] == np.unique(arr)[:, None]], names=[...])
```

Staying on arrow I couldn't not manage avoid looping 😭

```py
arr = table["foo"]
pa.Table.from_arrays([pc.equal(arr, v) for v in pc.unique(arr)], names=[...])
```

I didn't test which one is more perfomant

**Comment by MarcoGorelli** [comment]
converting to numpy will probably create issues is we've got missing values...

I think the second one you found is probably fine - we end up with a new column for each unique value, and we generally assume that for dataframe the number of columns isn't insanely huge (as opposed to the number of rows..)

**Comment by FBruzzesi** [comment]
Working on this!
