### ISSUE TITLE
[Bug]: pandas-like sorting in select can shuffle the index

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#581]
### Describe the bug

In pandas-like world, if we sort the first column in a select context, then the overall index changes. Is this expected behavior?

### Steps or code to reproduce the bug

Consider:

```py
import narwhals as nw
import pandas as pd

data = {"a": [1,3,2], "b": [0, 2, 1]}
df = nw.from_native(pd.DataFrame(data))
```

then:

```py
nw.to_native(df.select(nw.col("a").sort(), "b"))
``` 
```terminal
   a  b
0  1  0
2  2  2
1  3  1
```

while

```py
nw.to_native(df.select("a", nw.col("b").sort()))
```
```terminal
   a  b
0  1  0
1  3  1
2  2  2
```

### Expected results

In both cases the output index should end up being `[0,1,2]`

### Actual results

When sorting by the first expression, the index is adjusted accordingly

### Please run narwhals.show_version() and enter the output below.

```shell
System:
    python: 3.10.12 [GCC 11.4.0]

Python dependencies:
     narwhals: 1.1.4
       pandas: 2.2.2
       polars: 1.2.1
         cudf: 
        modin: 0.31.0
      pyarrow: 17.0.0
        numpy: 2.0.1
```

**Comment by MarcoGorelli** [comment]
thanks for the report - based on what I'd written in [for index alignment, we follow the left-hand-rule](https://narwhals-dev.github.io/narwhals/other/pandas_index/#2-index-alignment-follows-the-left-hand-rule), I think this is expected? is this causing issue for any use case?

**Comment by FBruzzesi** [comment]
> is this causing issue for any use case?

Not really, I noticed it while testing `.sort` with `nulls_last` argument - long story short, I was not able to use `compare_dicts` because of null vs none vs nan vs <NA> equalities, hence fallback to compare frames directly and pandas was failing due to index.

I solved it by moving the `.select(..., pl.col("b").sort(...)` after another column selection

**Comment by FBruzzesi** [comment]
Closing for now, I may add the example in the "What about pandas index?" example :)
