### ISSUE TITLE
feat: add methods to Dask backend

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#637]
Since #272  we have really minimal support for Dask DataFrame

Expr methods should go in `narwhals/_dask/expr.py`. For tests, you should use existing tests, and just remove the 
```
    if "dask" in str(constructor):
        request.applymarker(pytest.mark.xfail)
```
part. If you can remove that, and the test passes, it means you've done it correctly

## Not too hard

Examples of `Expr` methods which we should add (see [here](https://narwhals-dev.github.io/narwhals/api-reference/expr/) for the full list):
- `Expr.__sub__`
- `Expr.__mul__`
- `Expr.shift`
- `Expr.cum_sum`
- `Expr.is_between`

Note: we should not add anything which modifies the index. So, the following should _not_ be added, even though they appear on the list in the link above:
- Expr.sort
- Expr.head
- Expr.tail

## Harder

- `DataFrame.group_by`
- `DataFrame.filter`
- get things started with namespaces (e.g. `Expr.dt`, `Expr.str`, ...)

## General guidelines:
- please don't ask for the issue to be assigned to you
- please don't ask for permission to work on this issue
- if you're  a first time contribute, please choose 1 method at a time to implement, and leave a comment noting which method you're working on (if you've contributed to Narwhals before, feel free to choose multiple)
- have fun 🥳 

---

- Example pull request: https://github.com/narwhals-dev/narwhals/pull/731/files
- contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

---

An easy way to check if something still needs doing is to look for tests with
```
    if "dask" in str(constructor):
        request.applymarker(pytest.mark.xfail)
```
Then:
1. try removing those two lines
2. run the test, check that it fails
3. implement this functionality for Dask
4. check the test passes

**Comment by anopsy** [comment]
I'll take Expr.__sub__

**Comment by aidoskanapyanov** [comment]
I'll take `Expr.is_between`

**Comment by anopsy** [comment]
Taking `Expr.__mul__`

**Comment by DeaMariaLeon** [comment]
Take `Expr.sum`

**Comment by FBruzzesi** [comment]
@MarcoGorelli I have a couple of questions:

- Could you expand a little bit more, here or somewhere else on the following:
  > we should not add anything which modifies the index
- Should we refer to this issue also for dataframe methods? i.e. not Expr only?

**Comment by MarcoGorelli** [comment]
hey!

in pandas, some Series methods such as `Series.sort_values` change the index:
```
In [3]: s
Out[3]:
0    3
1    2
2    1
dtype: int64

In [4]: s.sort_values()
Out[4]:
2    1
1    2
0    3
dtype: int64
```

pandas / Dask would then auto-align on the index, which is what we want to avoid. in pandas we can just check the index values, as it's already eager, but in dask we don't have a way to do this (though I have opened an issue about this https://github.com/dask/dask-expr/issues/1112)

yup, dataframe methods too 😎

**Comment by anopsy** [comment]
I'm assuming Expr.min/Expr.max have also to be done, so I'll take those

**Comment by FBruzzesi** [comment]
(Asking for a friend 👀) how much cheating are we allowed to? Specifically, pandas-like `translate_dtype` should apply one-to-one for dask.

**Comment by MarcoGorelli** [comment]
😄 should be fine to reuse that one

**Comment by mistShard** [comment]
I'll look into `len` and `round`

**Comment by anopsy** [comment]
I'll try drop_nulls and count(not sure about count since it returns a Scalar)

**Comment by MarcoGorelli** [comment]
thanks! we have others that return scalars here, such as `sum` / `min` / ...

**Comment by mistShard** [comment]
I will add `Expr.abs`

**Comment by mistShard** [comment]
will take `Expr.all`

**Comment by anopsy** [comment]
I'll take `Expr.std` and `Expr.null_count`

**Comment by mistShard** [comment]
Ill take `is_unique`

**Comment by FBruzzesi** [comment]
Just to give a sense of how far we have gone and what's still missing.

`DaskExpr` methods (those marked with * at the end means that modify the index and require evaluation of #743 before implementing):

- [ ] `arg_true`
- [ ] `cast`
- [ ] `cat` (depends on `ExprCatNamespace`)
- [ ] `diff`
- [ ] `filter` (*)
- [ ] `gather_every` (*)
- [ ] `head` (*)
- [ ] `is_duplicated`
- [ ] `is_in`
- [ ] `is_unique`
- [ ] `null_count`
- [ ] `over`
- [ ] `quantile`
- [ ] `sample` (*)
- [ ] `tail` (*)
- [ ] `unique` (*)

`ExprDateTimeNamespace` methods:

- [ ] `to_string`
- [ ] `total_microseconds`
- [ ] `total_milliseconds`
- [ ] `total_minutes`
- [ ] `total_nanoseconds`
- [ ] `total_seconds`

`ExprCatNamespace` is missing entirely.

**Comment by anopsy** [comment]
I'm working on null_count and quantile.

**Comment by lucianosrp** [comment]
will work on `dt.to_string`

**Comment by FBruzzesi** [comment]
I will take a look at `cast` with some assumption on Dask dtypes as [discussed on discord](https://discord.com/channels/1235257048170762310/1237430779584446546/1272475408046100533)

**Comment by luke396** [comment]
will work on `total_microseconds`

**Comment by raisadz** [comment]
I will take `diff`

**Comment by benrutter** [comment]
I'll pick up `quantile`!

**Comment by aidoskanapyanov** [comment]
I'll take `cast`

**Comment by benrutter** [comment]
I'll take `concat` if nobody else has yet!

**Comment by FBruzzesi** [comment]
Closing this for now as the only methods which are left modify the index and #743 has just been closed
