### ISSUE TITLE
ci: put `MODIN_ENGINE=python` environment variable

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#673]
We should put `MODIN_ENGINE=python` as an environment variable in CI so that modin tests run more quickly

**Comment by FBruzzesi** [comment]
Added as repo env variable in [settings/variables/actions](https://github.com/narwhals-dev/narwhals/settings/variables/actions) as  explained in the [official guide](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository)
