### ISSUE TITLE
[Bug]: `DaskExpr` reduction to scalar can't be `select`-ed

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#694]
### Describe the bug

When selecting an expression which ends up in a reduction to a scalar, `AttributeError` is raised:

> AttributeError: 'Scalar' object has no attribute 'name'

### Steps or code to reproduce the bug

```py
import dask.dataframe as dd
import pandas as pd

df = nw.from_native(
    dd.from_pandas(
        pd.DataFrame(data={"a": [1., 3, 2]})
    )
)

for attr in ("min", "max", "mean", "sum"):
    try:
        df.select(getattr(nw.col("a"), attr)())
    except:
        print(f"{attr=} run into exception")
```

### Expected results

No error is thrown

### Actual results

AttributeError get raised

### Please run narwhals.show_version() and enter the output below.

```shell
main branch + 

System:
    python: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
executable: /home/fbruzzesi/open-source/narwhals/.venv/bin/python
   machine: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

Python dependencies:
     narwhals: 1.1.9
       pandas: 2.2.2
       polars: 1.2.1
         cudf: 
        modin: 0.31.0
      pyarrow: 17.0.0
        numpy: 2.0.1
```

### Relevant log output

<details>
<summary>Entire log</summary>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/open-source/narwhals/.venv/lib/python3.10/site-packages/dask_expr/_core.py:467, in Expr.__getattr__(self, key)
    466 try:
--> 467     return object.__getattribute__(self, key)
    468 except AttributeError as err:

File ~/open-source/narwhals/.venv/lib/python3.10/site-packages/dask_expr/_expr.py:448, in Expr.name(self)
    446 @property
    447 def name(self):
--> 448     return self._meta.name

AttributeError: 'numpy.float64' object has no attribute 'name'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
File ~/open-source/narwhals/.venv/lib/python3.10/site-packages/dask_expr/_collection.py:619, in FrameBase.__getattr__(self, key)
    616 try:
    617     # Fall back to `expr` API
    618     # (Making sure to convert to/from Expr)
--> 619     val = getattr(self.expr, key)
    620     if callable(val):

File ~/open-source/narwhals/.venv/lib/python3.10/site-packages/dask_expr/_core.py:488, in Expr.__getattr__(self, key)
    487 link = "https://github.com/dask-contrib/dask-expr/blob/main/README.md#api-coverage"
--> 488 raise AttributeError(
    489     f"{err}\n\n"
    490     "This often means that you are attempting to use an unsupported "
    491     f"API function. Current API coverage is documented here: {link}."
    492 )

AttributeError: 'numpy.float64' object has no attribute 'name'

This often means that you are attempting to use an unsupported API function. Current API coverage is documented here: https://github.com/dask-contrib/dask-expr/blob/main/README.md#api-coverage.

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[8], line 1
----> 1 df.select(getattr(nw.col("a"), attr)())

File ~/open-source/narwhals/narwhals/dataframe.py:2537, in LazyFrame.select(self, *exprs, **named_exprs)
   2371 def select(
   2372     self,
   2373     *exprs: IntoExpr | Iterable[IntoExpr],
   2374     **named_exprs: IntoExpr,
   2375 ) -> Self:
   2376     r"""
   2377     Select columns from this LazyFrame.
   2378 
   (...)
   2535         └───────────┘
   2536     """
-> 2537     return super().select(*exprs, **named_exprs)

File ~/open-source/narwhals/narwhals/dataframe.py:128, in BaseFrame.select(self, *exprs, **named_exprs)
    121 def select(
    122     self,
    123     *exprs: IntoExpr | Iterable[IntoExpr],
    124     **named_exprs: IntoExpr,
    125 ) -> Self:
    126     exprs, named_exprs = self._flatten_and_extract(*exprs, **named_exprs)
    127     return self._from_compliant_dataframe(
--> 128         self._compliant_frame.select(*exprs, **named_exprs),
    129     )

File ~/open-source/narwhals/narwhals/_dask/dataframe.py:87, in DaskLazyFrame.select(self, *exprs, **named_exprs)
     83 if exprs and all(isinstance(x, str) for x in exprs) and not named_exprs:
     84     # This is a simple slice => fastpath!
     85     return self._from_native_dataframe(self._native_dataframe.loc[:, exprs])
---> 87 new_series = parse_exprs_and_named_exprs(self, *exprs, **named_exprs)
     88 if not new_series:
     89     # return empty dataframe, like Polars does
     90     pd = get_pandas()

File ~/open-source/narwhals/narwhals/_dask/utils.py:53, in parse_exprs_and_named_exprs(df, *exprs, **named_exprs)
     51         raise TypeError(msg)
     52     for _result in _results:
---> 53         results[_result.name] = _result
     54 for name, value in named_exprs.items():
     55     _results = value._call(df)

File ~/open-source/narwhals/.venv/lib/python3.10/site-packages/dask_expr/_collection.py:625, in FrameBase.__getattr__(self, key)
    622     return val
    623 except AttributeError:
    624     # Raise original error
--> 625     raise err

File ~/open-source/narwhals/.venv/lib/python3.10/site-packages/dask_expr/_collection.py:614, in FrameBase.__getattr__(self, key)
    611 def __getattr__(self, key):
    612     try:
    613         # Prioritize `FrameBase` attributes
--> 614         return object.__getattribute__(self, key)
    615     except AttributeError as err:
    616         try:
    617             # Fall back to `expr` API
    618             # (Making sure to convert to/from Expr)

AttributeError: 'Scalar' object has no attribute 'name'

</details>

**Comment by MarcoGorelli** [comment]
yup - not really sure what to do about this one unfortunately...maybe we need a special case for when everything passed to `DaskLazyFrame.select` is actually a Dask Scalar, so then we can safely call `to_series` on each one of them and concat them

**Comment by FBruzzesi** [comment]
Mmmh I somehow manage to make reduction work properly, yet now breaks when broadcasting (e.g. `nw.col("a").min() + nw.col("b")` )🥲

I will try to spend some time on this
