### ISSUE TITLE
feat: Add clip expression to the api

### ISSUE THREAD

**Issue by aivanoved** [narwhals-dev/narwhals#700]
### Please describe the purpose of the new feature or describe the problem to solve.

It would be a nice QOL and likely a speed enhancement to have a `clip` expression in the api

Since it is a simple mathematical function, it seems like `polars` and `pandas` largely agree on the api, looking something like - `clip(lower_limit, upper_limit, *, **kwargs)`

### Suggest a solution if possible.

Adding a `polars` looking expression `clip(lower_bound, upper_bound)` would solve this issue

**Comment by cbourjau** [comment]
Thanks for looking into this! I suppose the API you are suggesting for narwhals is `clip(lower_limit, upper_limit)` (i.e., without the `kwargs`), isn't it?

**Comment by aivanoved** [comment]
@cbourjau

Thank you for the comment, yes, the api, which is suggested to be added is the `polars` version - `clip(lower_bound, upper_bound)`.

Will update the description to be clearer
