### ISSUE TITLE
Fill in missing docstrings

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#71]
# Add missing docstrings

Let's start with all the functions listed in https://narwhals-dev.github.io/narwhals/api-reference/expressions/. Feel free to divide the work up amongst yourselfs as you see fit. We need to gradually make sure they all have docstrings

## Steps

1. Pick a function you'd like to add a docstring for. For example, `Expr.alias`.
2. Make a new branch
3. Check the Polars docs to see what the function does: https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.alias.html
4. If applicable, re-use the same one-sentence summary and argument descriptions. Narwhals only implements a subset of Polars, so the Polars docs may have some extra bits which Narwhals doesn't support. If that's the case, leave the extra bits out
5. Add a one-sentence summary, and document the supported arguments
6. Make sure to include an example! More details below
7. run `mkdocs serve`, and open `http://127.0.0.1:8000/` (or whichever URL it gives you) in the browser. Find the example you added, and make sure it looks good
8. run `pytest narwhals --doctest-modules`, make sure it passes
9. `git add <files you've modified>`, `git commit -m '<you message goes here>'`, `git push origin HEAD`
10. open pull request

See https://github.com/narwhals-dev/narwhals/pull/74 for an example pull request

## Examples requirements

The examples should follow that pattern:
- import pandas, Polars, and Narwhals
- construct a `df_pd` pandas dataframe and a `df_pl` Polars dataframe
- write a dataframe-agnostic function `func` which uses the function you're writing a docstring for
- show the output when you pass either a pandas or a Polars dataframe

## Help

If you're stuck, feel free to ask here or on Discord. If you've got most of the way but are unsure about something, I'd suggest opening a draft pull request anyway - that's usually the fastest way to get help

## Contributing

See the [contributing guide](https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md) for how to get started

**Comment by hathawayj** [comment]
I will tackle `drop_nulls()`

**Comment by MatthewMec** [comment]
I will tackle csts(dftype).

**Comment by ugohuche** [comment]
I and Matthew would work on the first three - ```alias()```,  ```all()```, and ```any()```

**Comment by brentomagic** [comment]
i'll look into max().

**Comment by ugohuche** [comment]
Next I'll work on ```drop_nulls()``` to ```is_null()```

**Comment by anopsy** [comment]
I'll grab std() and mean()

**Comment by anopsy** [comment]
Btw I have a question, can I work on Narwhals using the codespaces on github? Given it's an open source project it should be for free, isn't?

**Comment by MarcoGorelli** [comment]
thanks all!

I've never used codespaces, so I don't know for sure...but I presume so? else, the contributing guide is here https://github.com/MarcoGorelli/narwhals/blob/main/CONTRIBUTING.md

**Comment by anopsy** [comment]
ah yes, contributing guide, it worth reading it anyway 😅

**Comment by shriyakalakata** [comment]
I'll work on min()

**Comment by brentomagic** [comment]
currently working on sum()

**Comment by brentomagic** [comment]
currently looking into unique()

**Comment by brentomagic** [comment]
working on n_unique()

**Comment by MarcoGorelli** [comment]
thanks all for your help! things are coming along really nicely

I've moved the page to https://narwhals-dev.github.io/narwhals/api-reference/expressions/, and have updated the link in the issue - if anyone was trying to reload the old link and it's not loading, then that's why

**Comment by shriyakalakata** [comment]
Working on `is_between()`

**Comment by natmokval** [comment]
I would like to work on `sample()` and `sort()`

**Comment by hathawayj** [comment]
> Next I'll work on `drop_nulls()` to `is_null()`

@ugohuche I will move to another and let you do `drop_nulls()` sorry for being behind.

**Comment by brentomagic** [comment]
looking into cast()

**Comment by MarcoGorelli** [comment]
i think @MatthewMec already has a pr open for that

**Comment by MarcoGorelli** [comment]
Looks like all the expression methods are taken. Nice work everyone 🤗 

What still needs doing:
- `Series` methods. The examples need to be a different there, see [Series.diff](https://narwhals-dev.github.io/narwhals/api-reference/series/#narwhals.series.Series.diff) for an example
- `Series.str` methods. We need a docstring for `.str.ends_with` (there's already one for `.str.to_datetime`)
- `Expr.str`, same as above
- `Series.dt` and `Expr.dt`. There's not much there yet so it should be easy
- `dependencies`: a few functions here need a docstring. It should just a one-liner, like there is for `get_pandas` and `get_polars`: https://narwhals-dev.github.io/narwhals/api-reference/dependencies/
- top-level functions (i.e. those in https://narwhals-dev.github.io/narwhals/api-reference/narwhals/): several functions here are missing docstrings. `concat`, for example`

In general, the format for docstrings should be:
1. import dependencies
2. create simple pandas and Polars objects, ideally with just one-liners
3. create a dataframe-agnostic function
4. show that passing pandas and Polars, we get the same output (and when we don't, like in `is_null`, explain why - like Uchenna did! 🙌 )

Note that some functions in `DataFrame` and `LazyFrame` don't quite follow that format, so we'll also need to update them to match the format

I'll open some other issues for other non-docstring-related work which needs doing, but let's keep this issue focused on docstrings

**Comment by brentomagic** [comment]
I'm working on .str.ends_with()

**Comment by InessaPawson** [comment]
I will work on:
`get_modin()`
`get_cudf()`
`get_pyarrow()`

**Comment by ugohuche** [comment]
I'll tackle ```Series.max```, ```Series.min``` and ```Series.mean```

**Comment by georgescutelnicu** [comment]
i'll take `Series.sum()`

**Comment by ugohuche** [comment]
I'll work on ```Expr.dt.year()```, ```Expr.dt.month()```, ```day()``` and ```hour()```

**Comment by brentomagic** [comment]
looking into `series.to_numpy` and `series.to_pandas`.

**Comment by natmokval** [comment]
I would like to work on `Series.is_in` and `Series.sample`

**Comment by brentomagic** [comment]
taking `series.filter()`

**Comment by natmokval** [comment]
I'm working on`Series.is_between` and `GroupBy.agg`

**Comment by brentomagic** [comment]
looking into `expr.filter()`

**Comment by MarcoGorelli** [comment]
Well done everybody, I think this can be closed (if there's any missing docstring, please do leave a comment / open a new issue / address it, I probably just missed it)

Great community effort here, thanks all! 🤗
