### ISSUE TITLE
[Enh]: Extend signature of supported methods

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#742]
### Please describe the purpose of the new feature or describe the problem to solve.

There are some methods for which we have partial support, meaning that not the full polars api is supported.

However this should be possible for some methods and/or some arguments (examples below)

### Additional information that may help us understand your needs.

Here a (partial) list of methods and arguments missing:

| method | missing argument(s) | note |
| --| --| -- |
| `DataFrame.drop` | `strict` | ✅ Fixed in #773 |
| `DataFrame.drop_nulls` | `subset` | ✅ Fixed in #779 |
| `DataFrame.join` | `suffix`| ✅ |
| `DataFrame.join_asof` | `suffix`, `tolerance` | |

**Comment by MarcoGorelli** [comment]
cool, happy to expand where it makes sense - if it's possible to get support across pandas/polars/pyarrow then it's probably already worth doing!

**Comment by FBruzzesi** [comment]
Closing this for now, we can come back to `join_asof` and other methods when and if required for adoption
