### ISSUE TITLE
Easy way to create nw.Series from numpy array

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#754]
We may need a convenience function outside of the Polars API for this, such as:
```python
s: nw.Series
m: np.ndarray
new_series = nw.new_series(m, native_namespace=s.__native_namespace__())
```

**Comment by FBruzzesi** [comment]
Related [scikit-lego PR](https://github.com/koaning/scikit-lego/pull/694) that workaround this using `nw.from_dict`
