### ISSUE TITLE
Don't require passing native_namespace to `nw.from_dict` if inputs are all nw.Series already

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#756]
The following should be supported:
```
data: dict[str, nw.Series]
nw.from_dict(data)
```

**Comment by matthewwardrop** [comment]
@MarcoGorelli: Hopefully with support for upgrading non nw.Series objects to nw.Series objects, and automatic casting of different backends to one consistent one. That would help in Formulaic :).

**Comment by MarcoGorelli** [comment]
thanks for your input!

Could you show an example of your use case please? Something like:
```python
import pandas as pd

data = {'a': polars_series, 'b': pandas_series}
nw.from_dict(data, native_namespace=pd)
```
?
Unfortunately, there's no standardised way of converting Series from one backend to a Series of a different backend

What you could do though is, if you wanted everything to be pandas-backed, is to use [Series.to_pandas](https://narwhals-dev.github.io/narwhals/api-reference/series/#narwhals.series.Series.to_pandas) and then [from_dict](https://narwhals-dev.github.io/narwhals/api-reference/narwhals/#narwhals.from_dict):
```
import pandas as pd

data = {'a': polars_series, 'b': pandas_series}
data_pd = {key: nw.from_native(value, series_only=True).to_pandas()}
nw.from_dict(data_pd, native_namespace=pd)
```
We should enable the same for PyArrow by adding `Series.to_arrow`: https://github.com/narwhals-dev/narwhals/issues/761

We also want to add something like `nw.new_series` https://github.com/narwhals-dev/narwhals/issues/754

Would these work for you?

**Comment by matthewwardrop** [comment]
Hi @MarcoGorelli ! Apologies for the delay.

Just wanted to clarify the intended implementation details here when there are potentially mixed datatypes:

```
import narwhals as nw
import pandas as pd
import polars as pl

a = nw.from_dict({'a': nw.from_native(pd.Series(['a', 'b', 'c']), series_only=True), 'b': nw.from_native(pl.Series(['a', 'b', 'c']), series_only=True)})
a.to_pandas()  # works
a.to_native()  # does not work (method does not exist)
```

Is this the intended behaviour for mixed datatypes? If so, would it be sensible to also auto-wrap native types in an `nw.Series` object when using `.from_dict`?

**Comment by MarcoGorelli** [comment]
hey! thanks for the example

This works because the pandas Series constructor happens to accept Polars Series (I haven't checked, but I think it might be because Polars Series implements `__array__`)
```python
In [4]: pd.Series(pl.Series([1,2,3]))
Out[4]:
0    1
1    2
2    3
dtype: int64
```

> a.to_native()  # does not work (method does not exist)

there's` nw.to_native`, so you can do
```
In [3]: a.pipe(nw.to_native)
Out[3]:
   a  b
0  a  a
1  b  b
2  c  c
```

At that point it's a pandas dataframe though - `from_dict` used the native namespace of the first `nw.Series` it encountered, which was pandas

> If so, would it be sensible to also auto-wrap native types in an nw.Series object when using .from_dict?

I'm not totally sure I understand the question, sorry 😳 But I'll explain what happens, perhaps that'll clarify things:
- the first `nw.Series` `from_dict` encounters is a pandas one
- `pd.DataFrame.from_dict` is called with all the native series in the dict:
    ```
    In [6]: pd.DataFrame.from_dict({'a': pd.Series(['a', 'b', 'c']), 'b': pl.Series(['a', 'b', 'c'])})
    Out[6]:
       a  b
    0  a  a
    1  b  b
    2  c  c
    ```
- the output from the last step is passed to `nw.from_native`
