### ISSUE TITLE
Support for categorical data types

### ISSUE THREAD

**Issue by cbourjau** [narwhals-dev/narwhals#79]
Apologies if I didn't find existing information about this! I am wondering if future support for categorical data types is in the envisioned scope of this very interesting project.

**Comment by MarcoGorelli** [comment]
Definitely!   Thanks for your interest

**Comment by MarcoGorelli** [comment]
@cbourjau just to know how to prioritise, do you have a use case where categorical data type is needed, or is this more of a general question?

**Comment by cbourjau** [comment]
Our feature engineering pipelines regularly process categorical data. Currently, they are built around Pandas, but I'd love to migrate them to Narwahls. The lack of categorical data types is thus far the only blocker I can see in our case.

**Comment by MarcoGorelli** [comment]
Cool - fancy sharing an example of what you do with categorical data? If we have an example of a dataframe-agnostic function you'd like to write, it'll be much easier

**Comment by cbourjau** [comment]
It is not trivial to say exactly which part of the Pandas API we use throughout our codebases with respect to categorical data types. However, I just noticed that narwhals is not complaining when presented with a data frame that has a categorical column - it is quietly passed through (which makes sense):

```python
import pandas as pd
import narwhals as nw

pdf = pd.DataFrame({"foo": ["bar", "baz"]}).astype({"foo": "category"})
ndf = nw.from_native(pdf)
assert isinstance(ndf.to_pandas()["foo"].dtype, pd.CategoricalDtype)
```

The categorical column can even be used:
```python
ndf.with_columns((nw.col("foo") == "baz").alias("buz")).to_pandas().dtypes
>>> foo    category
buz        bool
dtype: object
```
Is this by accident, or do you think this will continue to work? If so, I think this should be enough to get an internal prototype off the ground already! Whenever we do something more involved with categorical data, we may drop down to the native framework (Pandas, Polars, and an ONNX-based library, in our case). After that exercise we should have a clearer idea what is need to make the code framework agnostic. I'm afraid I don't have a timeline, but it seems that this is not blocking us from trying out narwhals.

**Comment by MarcoGorelli** [comment]
> Is this by accident, or do you think this will continue to work?

this'll continue to work, definitely. support in operations like `.cast` will come

**Comment by MarcoGorelli** [comment]
we've now got cast as well

closing for now then, but please do let me know if there's anything else we should do here, or anything else you'd like!
