### ISSUE TITLE
[Enh]: support mean_horizontal

### ISSUE THREAD

**Issue by eltoder** [narwhals-dev/narwhals#814]
### Please describe the purpose of the new feature or describe the problem to solve.

It would be great to add support for [`mean_horizontal`](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.mean_horizontal.html) from the polars API. Note that it is not the same as `sum_horizontal(cols) / N`, since it excludes null columns from mean.

**Comment by MarcoGorelli** [comment]
thanks @eltoder for your request! I think this would be in scope!
