### ISSUE TITLE
test: Get all cuDF tests passing

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#862]
We don't currently test cuDF in CI (though, hint hint, if anyone from Nvidia is passing by and wants to gift us with GPU minutes in CI...), we just do it manually on a Kaggle notebook: https://www.kaggle.com/code/marcogorelli/testing-cudf-in-narwhals

For a variety of reasons, some tests fail. Some examples:

### Ex. 1 cuDF doesn't implement something
```
FAILED tests/expr_and_series/dt/datetime_attributes_test.py::test_datetime_attributes[cudf_constructor-date-expected0] - AttributeError: 'DatetimeProperties' object has no attribute 'date'
```
Looks like cuDF doesn't implement `.dt.date`. There's not much we can do about this. So, in the test which hits this, we should `xfail` it if the constructor is `cuDF` (see some other test examples for how to xfail using pytest's `request.applymarker`)

### Ex. 2 test just fails
```
tests/expr_and_series/is_duplicated_test.py::test_is_duplicated_expr[cudf_constructor] - AssertionError
```
No details are given here, so this one requires investigation. Note that it also fails for Modin, so we might be using something in the implementation which only works for pandas

EDIT: some (all?) of these might already be resolved

### Ex. 3: cuDF intentionally raises

```
FAILED tests/frame/array_dunder_test.py::test_array_dunder_with_dtype[cudf_constructor] - ValueError: copy=False is not supported because conversion to a numpy array...
```
Like for `Ex. 1` cases, we should just `xfail` these tests

### Ex 4. Runtime Error
```
FAILED tests/expr_and_series/str/contains_test.py::test_contains[cudf_constructor] - RuntimeError: CUDF failure at:/opt/conda/conda-bld/work/cpp/src/strings/reg...
```
This might be a bug in cuDF? It might be worth reproducing it and reporting it to cuDF, and in the meantime, xfailing the test

### Ex 5. `AssertionError: (0.3, 0.3)`

`test_value_counts` shows this. We should investigate why - perhaps cuDF scalars also need porting to Python, like we do with PyArrow (`as_py`)?

**Comment by LiamConnors** [comment]
I'd like to try working through these if that's ok.

**Comment by MarcoGorelli** [comment]
of course, thanks @LiamConnors ! and please do ask if anything trips you up, either here or on Discord

**Comment by LiamConnors** [comment]
@MarcoGorelli there are a few tests that I see "`to_arrow` is not implemented for CuDF backend" on. Looks like it comes from here: https://github.com/narwhals-dev/narwhals/blob/main/narwhals/_pandas_like/dataframe.py#L678-L681 So I guess I'd `xfail` those tests, but would it want an issue to track implementation?

**Comment by LiamConnors** [comment]
Also was wondering about the recent tests changes https://github.com/narwhals-dev/narwhals/pull/918. The notebook has:

```
!cd narwhals && pytest -W ignore
```

which now throws this error:

```
_________________ ERROR collecting tpch/tests/test_queries.py __________________
ImportError while importing test module '/kaggle/working/narwhals/tpch/tests/test_queries.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/conda/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_queries'
```

I adjusted the command to run

```
!cd narwhals && pytest tests -W ignore
```

but not sure, should those tests in `tpch/tests` run too for the notebook?

**Comment by MarcoGorelli** [comment]
that's a good point, thanks @LiamConnors ! yup, `!cd narwhals && pytest tests -W ignore` should be perfect 🙌

**Comment by LiamConnors** [comment]
@MarcoGorelli for the example 5 you mention, I just want to make sure I understand correctly - do you mean convert the scalars to Python within the tests? I started looking at those ones and see that they are numpy data types
https://docs.rapids.ai/api/cudf/nightly/user_guide/data-types/#numpy-data-types so I started on this which gets the example you have above passing
https://github.com/narwhals-dev/narwhals/pull/987

**Comment by MarcoGorelli** [comment]
looks like cudf actually has a bug in nunique (https://github.com/rapidsai/cudf/issues/16861), kinda cool that the narwhals test suite helped find it. for now all we can do is xfail it, hopefully they'll fix it at some point

**Comment by LiamConnors** [comment]
Thanks @MarcoGorelli! Opened a PR for that one. Almost there with getting all the tests done!
I was wondering if you could help with this one: `test_actual_object` fails with

```
E   pyarrow.lib.ArrowInvalid: Could not convert <tests.frame.schema_test.test_actual_object.<locals>.Foo object at 0x7f95780e4910> with type Foo: did not recognize Python value type when inferring an Arrow data type
```

This PR seems to reference these files https://github.com/narwhals-dev/narwhals/pull/794/files 
You added modin to xfail there. Wondering what issue it was on that.

**Comment by MarcoGorelli** [comment]
sure - that one was to check that if we instantiate a dataframe with `Object` dtype - where "object" means a Python object, not a string in disguise as pandas-like dataframes do - that then the result schema would show up as `nw.Object`

It looks like cuDF doesn't let us instantiate such columns anyway

Maybe if we changed the test to do
```python
data = {'a': [1,2,3]}
df = nw.from_native(constructor_eager(data, dtype=object))
```
then that would pass, and would still capture the spirit of the test (object dtype which isn't strings in disguise)?

**Comment by LiamConnors** [comment]
Thanks @MarcoGorelli for the feedback! Still working on that one. 
The last few here are definitely the most challenging 😄 

Of what's remaining after https://github.com/narwhals-dev/narwhals/pull/1041
three are this failure, which I think might be related to the package versions installed in the notebook.

```
FAILED tests/series_only/to_dummy_test.py::test_to_dummies[cudf_constructor--] - NotImplementedError: Implemented only for data on CPU device
FAILED tests/series_only/to_dummy_test.py::test_to_dummies[cudf_constructor-_] - NotImplementedError: Implemented only for data on CPU device
FAILED tests/frame/null_count_test.py::test_null_count[cudf_constructor] - NotImplementedError: Implemented only for data on CPU device
```
It seems to come from `pyarrow`

```
pyarrow/array.pxi:2037: NotImplementedError
```
And there's a warning further up after installing pandas that
```
cudf 23.8.0 requires pyarrow==11.*, but you have pyarrow 17.0.0 which is incompatible.
```
But I couldn't get the tests to run after installing pyarrow 11. Will try running the tests with a later version of cuDF

**Comment by MarcoGorelli** [comment]
ah nice, so if we just upgrade cudf, then some of these fix themselves 😆 nice! https://www.kaggle.com/code/marcogorelli/testing-cudf-in-narwhals?scriptVersionId=197887672

Now we're only left with:
```
FAILED tests/test_group_by.py::test_no_agg[cudf_constructor] - TypeError: data must be list or dict-like
FAILED tests/frame/to_dict_test.py::test_to_dict[cudf_constructor] - TypeError: DataFrame.to_dict() got an unexpected keyword argument 'index'
FAILED tests/frame/schema_test.py::test_actual_object[cudf_constructor] - pyarrow.lib.ArrowInvalid: Could not convert <tests.frame.schema_test.test_a...
```

We should also see if
```
# this segfaults(!)
!cd narwhals && rm tests/series_only/to_numpy_test.py
```
is now addressed

**Comment by LiamConnors** [comment]
Thanks. Will check `!cd narwhals && rm tests/series_only/to_numpy_test.py`

This one seems to be new:
```FAILED tests/frame/to_dict_test.py::test_to_dict[cudf_constructor] - TypeError: DataFrame.to_dict() got an unexpected keyword argument 'index'``` 

But it's fixed if we update the pandas version:

```
!pip install pandas==2.2.2
```

Instead of 1.5. The older pandas version isn't compatible with the newer cudf, so seems like the reason. `index` was added in Pandas 2.

```
cudf-cu12 24.8.3 requires pandas<2.2.3dev0,>=2.0, but you have pandas 1.5.0 which is incompatible.
```

**Comment by MarcoGorelli** [comment]
ooh nice, this keeps getting better

in the latest run https://www.kaggle.com/code/marcogorelli/testing-cudf-in-narwhals?scriptVersionId=197913379, we only see

```
FAILED tests/series_only/to_numpy_test.py::test_to_numpy[cudf_constructor] - ValueError: Column must have no nulls.
FAILED tests/frame/schema_test.py::test_actual_object[cudf_constructor] - pyarrow.lib.ArrowInvalid: Could not convert <tests.frame.schema_test.test_a...
FAILED tests/test_group_by.py::test_no_agg[cudf_constructor] - TypeError: data must be list or dict-like
```

**Comment by LiamConnors** [comment]
I see a number of new failures about iteration. Not really sure if it's an issue with 
https://github.com/narwhals-dev/narwhals/blob/main/tests/utils.py needing some update or something with `__iter__` support. 

```
TypeError: Series object is not iterable. Consider using `.to_arrow()

```

For example

```
____________________ test_meanh[cudf_constructor-col_expr0] ____________________

constructor = <function cudf_constructor at 0x7cbb24841000>
col_expr = <narwhals.stable.v1.Expr object at 0x7cba722644f0>

    @pytest.mark.parametrize("col_expr", [nw.col("a"), "a"])
    def test_meanh(constructor: Constructor, col_expr: Any) -> None:
        data = {"a": [1, 3, None, None], "b": [4, None, 6, None]}
        df = nw.from_native(constructor(data))
        result = df.select(horizontal_mean=nw.mean_horizontal(col_expr, nw.col("b")))
        expected = {"horizontal_mean": [2.5, 3.0, 6.0, float("nan")]}
>       compare_dicts(result, expected)

tests/expr_and_series/mean_horizontal_test.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/utils.py:37: in compare_dicts
    for lhs, rhs in zip_strict(result[key], expected[key]):
narwhals/series.py:2477: in __iter__
    yield from self._compliant_series.__iter__()
narwhals/_pandas_like/series.py:670: in __iter__
    yield from self._native_series.__iter__()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = 0    2.5
1    3.0
2    6.0
3    NaN
Name: horizontal_mean, dtype: float64

    def __iter__(self):
        """
        Iteration is unsupported.
    
        See :ref:`iteration <pandas-comparison/iteration>` for more
        information.
        """
>       raise TypeError(
            f"{self.__class__.__name__} object is not iterable. "
            f"Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` "
            f"if you wish to iterate over the values."
        )
E       TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` if you wish to iterate over the values.
```

**Comment by LiamConnors** [comment]
> I see a number of new failures about iteration. Not really sure if it's an issue with https://github.com/narwhals-dev/narwhals/blob/main/tests/utils.py needing some update or something with `__iter__` support.
> 
> ```
> TypeError: Series object is not iterable. Consider using `.to_arrow()
> ```
> 
> For example
> 
> ```
> ____________________ test_meanh[cudf_constructor-col_expr0] ____________________
> 
> constructor = <function cudf_constructor at 0x7cbb24841000>
> col_expr = <narwhals.stable.v1.Expr object at 0x7cba722644f0>
> 
>     @pytest.mark.parametrize("col_expr", [nw.col("a"), "a"])
>     def test_meanh(constructor: Constructor, col_expr: Any) -> None:
>         data = {"a": [1, 3, None, None], "b": [4, None, 6, None]}
>         df = nw.from_native(constructor(data))
>         result = df.select(horizontal_mean=nw.mean_horizontal(col_expr, nw.col("b")))
>         expected = {"horizontal_mean": [2.5, 3.0, 6.0, float("nan")]}
> >       compare_dicts(result, expected)
> 
> tests/expr_and_series/mean_horizontal_test.py:16: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> tests/utils.py:37: in compare_dicts
>     for lhs, rhs in zip_strict(result[key], expected[key]):
> narwhals/series.py:2477: in __iter__
>     yield from self._compliant_series.__iter__()
> narwhals/_pandas_like/series.py:670: in __iter__
>     yield from self._native_series.__iter__()
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = 0    2.5
> 1    3.0
> 2    6.0
> 3    NaN
> Name: horizontal_mean, dtype: float64
> 
>     def __iter__(self):
>         """
>         Iteration is unsupported.
>     
>         See :ref:`iteration <pandas-comparison/iteration>` for more
>         information.
>         """
> >       raise TypeError(
>             f"{self.__class__.__name__} object is not iterable. "
>             f"Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` "
>             f"if you wish to iterate over the values."
>         )
> E       TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` if you wish to iterate over the values.
> ```

Ah okay, so I guess when `zip_strict` was called previously, it was using `__getitem__` but now uses `__iter__` and that's not working for cuDF. Would that be something to change in the tests only or on the `nw.Series` itself?

**Comment by MarcoGorelli** [comment]
ah interesting thanks - perhaps in 

https://github.com/narwhals-dev/narwhals/blob/9c5af5f0269d4e35f6225df7a1c9bcbf10e35e68/tests/utils.py#L36-L37

we should instead do
```python
result_key = result[key]
if nw.dependencies.is_cudf_series(result_key):
    result_key = result_key.to_pandas()
for lhs, rhs in zip(result_key, expected[key]):
```
?

**Comment by LiamConnors** [comment]
> ```python
> nw.dependencies.is_cudf_series(result_key):
> ```

Thanks @MarcoGorelli!
Taking a look at this. `is_cudf_series` check doesn't seem to work. I guess because it's generally a narwhals series object `narwhals.stable.v1.Series` that is the `result_key`?

Have the following working, but couldn't find a better way to check if it's a cuDF series.

```
result_key = result[key]
if hasattr(result_key, "_compliant_series") and "CUDF" in str(
    result_key._compliant_series._implementation
):
    result_key = result_key.to_pandas()
```

**Comment by LiamConnors** [comment]
> sure - that one was to check that if we instantiate a dataframe with `Object` dtype - where "object" means a Python object, not a string in disguise as pandas-like dataframes do - that then the result schema would show up as `nw.Object`
> 
> It looks like cuDF doesn't let us instantiate such columns anyway
> 
> Maybe if we changed the test to do
> 
> ```python
> data = {'a': [1,2,3]}
> df = nw.from_native(constructor_eager(data, dtype=object))
> ```
> 
> then that would pass, and would still capture the spirit of the test (object dtype which isn't strings in disguise)?

Still looking at this one. So far I've found that for cudf this:

```
df = nw.from_native(constructor_eager(data, dtype=object))
```

ends up as 

```
Schema([('a', String)])
```

Looks like this check here returns a string: https://github.com/narwhals-dev/narwhals/blob/main/narwhals/_pandas_like/utils.py#L284-L292

**Comment by MarcoGorelli** [comment]
the tz_aware one failing looks like a bug in cudf too https://github.com/rapidsai/cudf/issues/16973

**Comment by LiamConnors** [comment]
> the tz_aware one failing looks like a bug in cudf too [rapidsai/cudf#16973](https://github.com/rapidsai/cudf/issues/16973)

Thanks! Marked that as `xfail` here https://github.com/narwhals-dev/narwhals/pull/1118
Back to just two failing tests now! Will try and investigate those further this week.

**Comment by LiamConnors** [comment]
Opened a draft PR to get the last test passing: https://github.com/narwhals-dev/narwhals/pull/1138

Marked as draft because I'm not sure 100% if it's something we should update or if maybe it's a cuDF bug.

<img width="848" alt="image" src="https://github.com/user-attachments/assets/9c2acb42-307b-45af-a0a6-44543879b872">

**Comment by LiamConnors** [comment]
There's a new failure happening:

```
>               raise ValueError("all cols in value_vars must have the same dtype")
E               ValueError: all cols in value_vars must have the same dtype

/opt/conda/lib/python3.10/site-packages/cudf/core/reshape.py:615: ValueError
=========================== short test summary info ============================
FAILED tests/frame/unpivot_test.py::test_unpivot_mixed_types[cudf_constructor-data0-expected_dtypes0] - ValueError: all cols in value_vars must have the same dtype
====== 1 failed, 4695 passed, 14 skipped, 142 xfailed in 76.04s (0:01:16) ======
```

Taking a look.
