### ISSUE TITLE
test: run Dask tests with `npartitions=2`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#872]
If we use `npartitions=2` in the Dask constructor, some tests fail

I think this is just in cases when Dask may shuffle row order, which we can probably resolve by including an `'i'` column which just enumerates the rows, and then sorting by that at the end

This would also help make the test suite more resilient for future lazy backends

---

I'll add some more details later, sorry if this is unclear

**Comment by FBruzzesi** [comment]
Pinning down the remaining cases that are failing:

- `DaskLazyFrame.tail`: unlike `head` method which has a `npartitions` argument to scan, `tail` does not allow that. The hack could be to repartition on behalf on the user, even though I am not really comfortable with it. Namely:
    ```diff
    + return self._from_native_frame(self._native_frame.repartition(npartitions=1).tail(n=n, compute=False))
    - return self._from_native_frame(self._native_frame.tail(n=n, compute=False))
    ```
- `DaskLazyFrame.filter` with boolean list: this is something I would be happy to not allow. See somewhat related [discord discussion](https://discord.com/channels/1235257048170762310/1237430779584446546/1279509792821608490) as well.
- `DaskExpr.over`: ends up with the following error: `ValueError: cannot reindex on an axis with duplicate labels`
- `DaskExpr.quantile`: I see no options for this method, and would not know how to fix the issue

**Comment by MarcoGorelli** [comment]
thanks @FBruzzesi ! shall we just raise notimplementederror for these then and xfail tests?

**Comment by MarcoGorelli** [comment]
if we can inspect `npartitions` of an object, then I think so, sure
