### ISSUE TITLE
[Doc]: Check marks on API Completeness – Expr page broken

### ISSUE THREAD

**Issue by firai** [narwhals-dev/narwhals#878]
### What type of report is this?

Correction

### Please describe the issue.

The check marks on  [API Completeness – Expr](https://narwhals-dev.github.io/narwhals/api-completeness/expr/) seem to be broken

**Comment by MarcoGorelli** [comment]
yup, thanks @firai for the report

@FBruzzesi fancy taking a look?

**Comment by FBruzzesi** [comment]
Thanks for reporting the issue. If I run `mkdocs serve` locally, it renders as expected so I am a bit lost on the reason for this.
The only idea I can think of is to increase `set_tbl_width_chars`. Some trial and errors are coming 😇
