### ISSUE TITLE
feat: join_asof

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#896]
I saw this here https://www.linkedin.com/posts/dawie-diamond-51089676_bladetiptiming-rotordynamics-testandmeasurement-ugcPost-7235944133633159168-weqn?utm_source=share&utm_medium=member_desktop, and `join_asof` would probably help

library: https://github.com/Bladesight/Bladesight/pull/38

**Comment by raisadz** [comment]
I will take it

**Comment by MarcoGorelli** [comment]
closed by  #911
