### ISSUE TITLE
add `pre-commit` to contributing.md

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#90]
looks like I left this out of the contributing guide initially

we just need to add a sentence advising something like

> You should also install `pre-commit`:
> ```
> pip install pre-commit
> pre-commit install
> ```
> so that, when you make a commit, the formatting and linting happens automatically and blocks the commit if something goes wrong.

**Comment by shriyakalakata** [comment]
I'd like to work on this!
