### ISSUE TITLE
[Bug]: pandas-like fails for no aggregations in group by context

### ISSUE THREAD

**Issue by FBruzzesi** [narwhals-dev/narwhals#943]
### Describe the bug

> RuntimeError: Congrats, you entered unreachable code. Please report a bug to https://github.com/narwhals-dev/narwhals/issues.

Do I win something? Empty aggs are allowed in polars, but we enter unreachable code in pandas-like 😂

### Steps or code to reproduce the bug

```py
import narwhals as nw
import pandas as pd
import polars as pl

@nw.narwhalify
def func(df):
    return df.group_by("a").agg() 

data = {"a": [0, 0, 2, -1], "b": [1, 3, 2, None]}
```
- pandas:
    ```py
    func(pd.DataFrame(data))
    ```
     > RuntimeError: Congrats, you entered unreachable code. Please report a bug to https://github.com/narwhals-dev/narwhals/issues.

- polars:
    ```py
    func(pl.DataFrame(data))
    ```
    ```terminal
    shape: (3, 1)
    ┌─────┐
    │ a   │
    │ --- │
    │ i64 │
    ╞═════╡
    │ 2   │
    │ 0   │
    │ -1  │
    └─────┘
    ```

- pyarrow:
    ```py
    func(pa.table(data))
    ```

    ```terminal
    pyarrow.Table
    a: int64
    ----
    a: [[0,2,-1]]
    ```

### Expected results

Return the group(s) keys for pandas-like as well

### Actual results

pandas-like raises
polars returns group keys
pyarrow returns group keys

### Please run narwhals.show_version() and enter the output below.

```shell
System:
    python: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
   machine: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

Python dependencies:
     narwhals: 1.6.4
       pandas: 2.2.2
       polars: 1.5.0
         cudf: 
        modin: 0.31.0
      pyarrow: 17.0.0
        numpy: 2.0.1
```

**Comment by MarcoGorelli** [comment]
Yup! Please present yourself to the Narwhals HQ in the Canadian High Arctic to redeem your prize 🏆
