### ISSUE TITLE
[Enh]: Use offical `astral-sh/setup-uv@v2` github action and enable caching in the CI

### ISSUE THREAD

**Issue by aidoskanapyanov** [narwhals-dev/narwhals#955]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

No response

### Please describe the purpose of the new feature or describe the problem to solve.

- We should use an official github action to install `uv` onto the running CI platform
- We can speed up the `uv install` CI step by caching the dependencies, since `requirements-dev.txt` does not change so often.

### Suggest a solution if possible.

```diff
...
        with:
          python-version: ${{ matrix.python-version }}
-     - name: Install uv (Unix)
-       if: runner.os != 'Windows'
-       run: curl -LsSf https://astral.sh/uv/install.sh | sh
-     - name: Install uv (Windows)
-       if: runner.os == 'Windows'
-       run: powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
+     - name: Install the latest version of uv
+       uses: astral-sh/setup-uv@v2
+       with:
+         version: "latest"
+     - name: Enable caching
+       id: setup-uv
+       uses: astral-sh/setup-uv@v2
+       with:
+         enable-cache: true
+         cache-suffix: "reqs-cache"
      - name: install-reqs
...
```

**Comment by MarcoGorelli** [comment]
sounds good, thanks - were you interested in making a pr with that suggested change?

**Comment by aidoskanapyanov** [comment]
Yeah, thanks, I'll draft a PR on these changes. I also need to read on `cache-suffix`, and see if I need a unique suffix for each workflow.
