### ISSUE TITLE
[Enh]: Random seed for `sample`

### ISSUE THREAD

**Issue by wd60622** [narwhals-dev/narwhals#973]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

I would like to use the `sample` method that allows for reproducibility. However, there is no random state parameter

### Please describe the purpose of the new feature or describe the problem to solve.

Reproducibility

### Suggest a solution if possible.

New parameter

**Comment by FBruzzesi** [comment]
Thanks for reporting this issue. It is certainly something in scope
