### ISSUE TITLE
[Bug]: Subsetting 0 rows or 0 columns returns returns unexpected behavior

### ISSUE THREAD

**Issue by schloerke** [narwhals-dev/narwhals#989]
### Describe the bug

Unexpected row subset behaviors:
* When performing an empty row subset on pandas, it returns an empty column data frame. This does not happen with polars
* When performing an empty row and an column slice subset on both pandas an polars, an error is thrown: `TypeError: Expected slice of integers or strings, got: <class 'slice'>`

Unexpected column subset behaviors:
* When performing an empty column subset on pandas, it returns an data frame with `nrow` rows and 0 columns. This does not happen with polars.

Unexpected row/column subset behavior
* When performing an empty slice row and empty slice column subset on both pandas an polars, an error is thrown: `TypeError: Expected slice of integers or strings, got: <class 'slice'>`

Links to docs where examples were inspired from: 
https://narwhals-dev.github.io/narwhals/api-reference/dataframe/#narwhals.dataframe.DataFrame.__getitem__

(Other data types are untested)

### Steps or code to reproduce the bug

```python
import narwhals as nw
import pandas as pd
import polars as pl

DATA={ "x": [1,2,3] }
pd_df = nw.from_native(pd.DataFrame(DATA), eager_only=True)
pl_df = nw.from_native(pl.DataFrame(DATA), eager_only=True)

print("nw row subset.\nExpecting (0, 3)")

# This should return 0 rows and all columns. 
# Currently it returns all rows and 0 columns
print("pd_df[[]].shape (bad):", pd_df[[]].shape)
print("pl_df[[]].shape (good!):", pl_df[[]].shape)

# This should return 0 rows and all columns. 
# Currently it raises an error: 
# TypeError: Expected slice of integers or strings, got: <class 'slice'>
try:
    pd_df[[], :].shape
except TypeError as e:
    print("pd_df[[], :].shape Error:", str(e))
try:
    pl_df[[], :].shape
except TypeError as e:
    print("pl_df[[], :].shape Error:", str(e))

# Work around: 0 rows and all columns
print("pd_df[[], pd_df.columns].shape", pd_df[[], pd_df.columns].shape)
print("pl_df[[], pl_df.columns].shape", pl_df[[], pl_df.columns].shape)


print("-----------------")
print("nw col subset.\nExpecting (0, 0) because if there are no Series objects, then there are no rows")

print("pd_df[:, []].shape (bad):", pd_df[:, []].shape)
print("pl_df[:, []].shape (good!):", pl_df[:, []].shape)

try:
    pd_df[:, :].shape
except TypeError as e:
    print("pd_df[:, :].shape Error:", str(e))
try:
    pl_df[:, :].shape
except TypeError as e:
    print("pl_df[:, :].shape Error:", str(e))

print("pd_df[[], []].shape (good!):", pd_df[[], []].shape)
print("pl_df[[], []].shape (good!):", pl_df[[], []].shape)

print("-----------------")
print("nw.show_versions()")
nw.show_versions()
```

### Expected results

* These row subsets should always return a `.shape` of `(0, COL_LEN)`.
	* `df[[]].shape`; (broken for pandas)
	* `df[[], :].shape`
* These column subsets above should always return a `.shape` of `(0, 0)`. If there are no Series objects to hold the data, then there should be 0 rows.
	* `df[:, []].shape`; (broken for pandas)
	* `df[:, []].shape`
* I'd expect `df[:, :]` to return `df`

### Actual results

```python
nw row subset.
Expecting (0, 3)
pd_df[[]].shape (bad): (3, 0)
pl_df[[]].shape (good!): (0, 1)
pd_df[[], :].shape Error: Expected slice of integers or strings, got: <class 'slice'>
pl_df[[], :].shape Error: Expected slice of integers or strings, got: <class 'slice'>
pd_df[[], pd_df.columns].shape (0, 1)
pl_df[[], pl_df.columns].shape (0, 1)
-----------------
nw col subset.
Expecting (0, 0) because if there are no Series object, then there are no rows
pd_df[:, []].shape (bad): (3, 0)
pl_df[:, []].shape (good!): (0, 0)
pd_df[:, :].shape Error: Expected slice of integers or strings, got: <class 'slice'>
pl_df[:, :].shape Error: Expected slice of integers or strings, got: <class 'slice'>
pd_df[[], []].shape (good!): (0, 0)
pl_df[[], []].shape (good!): (0, 0)
```

### Please run narwhals.show_version() and enter the output below.

```shell
System:
    python: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
executable: [/path/to/python](https://file+.vscode-resource.vscode-cdn.net/path/to/python)
   machine: macOS-14.6.1-arm64-arm-64bit

Python dependencies:
     narwhals: 1.8.1
       pandas: 2.2.2
       polars: 1.5.0
         cudf: 
        modin: 
      pyarrow: 
        numpy: 2.1.0
```

**Comment by MarcoGorelli** [comment]
thanks @schloerke for the report!

**Comment by MarcoGorelli** [comment]
> ```
> print("nw row subset.\nExpecting (0, 3)")
> 
> # This should return 0 rows and all columns. 
> # Currently it returns all rows and 0 columns
> print("pd_df[[]].shape (bad):", pd_df[[]].shape)
> print("pl_df[[]].shape (good!):", pl_df[[]].shape)
> ```

Was this meant to be `"Expecting (0, 3)"`? the data has a single column, so no rows and all columns would have shape `(0, 1)`

**Comment by schloerke** [comment]
> Was this meant to be `"Expecting (0, 3)"`? the data has a single column, so no rows and all columns would have shape `(0, 1)`

Yes. So sorry. Thank you!

(Yes. A data frame can have many column with 0 rows.)

**Comment by raisadz** [comment]
I would like to work on it if that's ok
