### ISSUE TITLE
docs: include PyArrow in quick start

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#997]
Currently, https://narwhals-dev.github.io/narwhals/quick_start/ only shows the output for pandas and Polars

Let's get PyArrow in there too?

---

file to modify: https://github.com/narwhals-dev/narwhals/blob/main/docs/quick_start.md

contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

**Comment by sTomerG** [comment]
@MarcoGorelli both https://narwhals-dev.github.io/narwhals/quick_start/ and https://github.com/narwhals-dev/narwhals/blob/main/docs/quick_start.md return `404`

**Comment by juanchodpg2** [comment]
I would like to work on this.
