### ISSUE TITLE
docs: include PyArrow in Tutorial/DataFrame

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#998]
In https://narwhals-dev.github.io/narwhals/basics/dataframe/ we only show pandas + Polars. Let's get PyArrow in there too?

I'd suggest:
- for all except for "example 3", we could have tabs for: pandas, Polars[lazy], PyArrow
- for example 3, we could have: pandas, Polars[eager], PyArrow

---

file to modify: https://github.com/narwhals-dev/narwhals/blob/main/docs/basics/dataframe.md

contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

**Comment by mattcristal** [comment]
I would like to work on this one!
