### ISSUE TITLE
docs: include PyArrow in Tutorial/Series

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#999]
In https://narwhals-dev.github.io/narwhals/basics/series/ we only show pandas + Polars. Let's get PyArrow in there too?

I'd suggest:
- for all except for "example 4", we could have tabs for: pandas, Polars[lazy], PyArrow
- for example 4, we could have: pandas, Polars[eager], PyArrow

---

file to modify: https://github.com/narwhals-dev/narwhals/blob/main/docs/basics/column.md

contributing guide: https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md

while you're here, you can also rename the file from `column.md` to `series.md` (you'll also need to make this change in `mkdocs.yml`

**Comment by gauthierpiarrette** [comment]
Happy to work on this one!
